<?php

namespace Macmotp\Countries\Support;

use Macmotp\Country;
use Macmotp\Countries\AD;
use Macmotp\Countries\AE;
use Macmotp\Countries\AF;
use Macmotp\Countries\AG;
use Macmotp\Countries\AI;
use Macmotp\Countries\IT;
use Macmotp\Countries\US;

/**
 * Context class
 *
 * Mapping each country code with related implementation
 */
final class Context
{
    /**
     * Map country codes with related interface
     *
     * @param string $countryCode
     *
     * @return CountryInterface
     */
    public static function getFromCode(string $countryCode): CountryInterface
    {
        return match ($countryCode) {
            Country::AD => new AD(),
            Country::AE => new AE(),
            Country::AF => new AF(),
            Country::AG => new AG(),
            Country::AI => new AI(),
            Country::IT => new IT(),
            default => new US(),
        };
    }

    /**
     * Return a Collection with all the currencies
     *
     * @return Collection
     */
    public static function getAll(): Collection
    {
        return new Collection([
            new AD(),
            new AE(),
            new AF(),
            new AG(),
            new AI(),
            new US(),
        ]);

        $list = [


            'AL' => [
                'continent' => 'Europe',
                'name' => 'Albania',
                'alpha3_code' => 'ALB',
                'dial_code' => '+355',
                'default_timezone' => 'Europe/Tirane',
                'default_language' => Language::ITALIAN,
            ],
            'AM' => [
                'continent' => 'Asia',
                'name' => 'Armenia',
                'alpha3_code' => 'ARM',
                'dial_code' => '+374',
                'default_timezone' => 'Asia/Yerevan',
                'default_language' => Language::ENGLISH,
            ],
            'AO' => [
                'continent' => 'Africa',
                'name' => 'Angola',
                'alpha3_code' => 'AGO',
                'dial_code' => '+244',
                'default_timezone' => 'Africa/Luanda',
                'default_language' => Language::ENGLISH,
            ],
            'AQ' => [
                'continent' => 'Antarctica',
                'name' => 'Antarctica',
                'alpha3_code' => 'ATA',
                'dial_code' => '+672',
                'default_timezone' => 'Antarctica/McMurdo',
                'default_language' => Language::ENGLISH,
            ],
            'AR' => [
                'continent' => 'South America',
                'name' => 'Argentina',
                'alpha3_code' => 'ARG',
                'dial_code' => '+54',
                'default_currency_code' => Currency::ARS,
                'default_timezone' => 'America/Argentina/Buenos_Aires',
                'default_language' => Language::SPANISH,
            ],
            'AS' => [
                'continent' => 'Oceania',
                'name' => 'American Samoa',
                'alpha3_code' => 'ASM',
                'dial_code' => '+1684',
                'default_timezone' => 'Pacific/Pago_Pago',
                'default_language' => Language::ENGLISH,
            ],
            'AT' => [
                'continent' => 'Europe',
                'name' => 'Austria',
                'alpha3_code' => 'AUT',
                'dial_code' => '+43',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Vienna',
                'default_language' => Language::GERMAN,
            ],
            'AU' => [
                'continent' => 'Oceania',
                'name' => 'Australia',
                'alpha3_code' => 'AUS',
                'dial_code' => '+61',
                'default_currency_code' => Currency::AUD,
                'default_timezone' => 'Australia/Melbourne',
                'default_language' => Language::ENGLISH,
            ],
            'AW' => [
                'continent' => 'North America',
                'name' => 'Aruba',
                'alpha3_code' => 'ABW',
                'dial_code' => '+297',
                'default_timezone' => 'America/Aruba',
                'default_language' => Language::ENGLISH,
            ],
            'AX' => [
                'continent' => 'Europe',
                'name' => 'Åland',
                'alpha3_code' => 'ALA',
                'dial_code' => '+358',
                'default_timezone' => 'Europe/Mariehamn',
                'default_language' => Language::ENGLISH,
            ],
            'AZ' => [
                'continent' => 'Asia',
                'name' => 'Azerbaijan',
                'alpha3_code' => 'AZE',
                'dial_code' => '+994',
                'default_timezone' => 'Asia/Baku',
                'default_language' => Language::ENGLISH,
            ],
            'BA' => [
                'continent' => 'Europe',
                'name' => 'Bosnia and Herzegovina',
                'alpha3_code' => 'BIH',
                'dial_code' => '+387',
                'default_timezone' => 'Europe/Sarajevo',
                'default_language' => Language::ENGLISH,
            ],
            'BB' => [
                'continent' => 'North America',
                'name' => 'Barbados',
                'alpha3_code' => 'BRB',
                'dial_code' => '+1246',
                'default_timezone' => 'America/Barbados',
                'default_language' => Language::ENGLISH,
            ],
            'BD' => [
                'continent' => 'Asia',
                'name' => 'Bangladesh',
                'alpha3_code' => 'BGD',
                'dial_code' => '+880',
                'default_timezone' => 'Asia/Dhaka',
                'default_language' => Language::ENGLISH,
            ],
            'BE' => [
                'continent' => 'Europe',
                'name' => 'Belgium',
                'alpha3_code' => 'BEL',
                'dial_code' => '+32',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Brussels',
                'default_language' => Language::FRENCH,
            ],
            'BF' => [
                'continent' => 'Africa',
                'name' => 'Burkina Faso',
                'alpha3_code' => 'BFA',
                'dial_code' => '+226',
                'default_timezone' => 'Africa/Ouagadougou',
                'default_language' => Language::FRENCH,
            ],
            'BG' => [
                'continent' => 'Europe',
                'name' => 'Bulgaria',
                'alpha3_code' => 'BGR',
                'dial_code' => '+359',
                'default_currency_code' => Currency::BGN,
                'default_timezone' => 'Europe/Sofia',
                'default_language' => Language::ENGLISH,
            ],
            'BH' => [
                'continent' => 'Asia',
                'name' => 'Bahrain',
                'alpha3_code' => 'BHR',
                'dial_code' => '+973',
                'default_timezone' => 'Asia/Bahrain',
                'default_language' => Language::ENGLISH,
            ],
            'BI' => [
                'continent' => 'Africa',
                'name' => 'Burundi',
                'alpha3_code' => 'BDI',
                'dial_code' => '+257',
                'default_timezone' => 'Africa/Bujumbura',
                'default_language' => Language::ENGLISH,
            ],
            'BJ' => [
                'continent' => 'Africa',
                'name' => 'Benin',
                'alpha3_code' => 'BEN',
                'dial_code' => '+229',
                'default_timezone' => 'Africa/Porto-Novo',
                'default_language' => Language::ENGLISH,
            ],
            'BL' => [
                'continent' => 'North America',
                'name' => 'Saint Barthélemy',
                'alpha3_code' => 'BLM',
                'dial_code' => '+590',
                'default_timezone' => 'America/St_Barthelemy',
                'default_language' => Language::FRENCH,
            ],
            'BM' => [
                'continent' => 'North America',
                'name' => 'Bermuda',
                'alpha3_code' => 'BMU',
                'dial_code' => '+1441',
                'default_timezone' => 'Atlantic/Bermuda',
                'default_language' => Language::ENGLISH,
            ],
            'BN' => [
                'continent' => 'Asia',
                'name' => 'Brunei',
                'alpha3_code' => 'BRN',
                'dial_code' => '+673',
                'default_currency_code' => Currency::SGD,
                'default_timezone' => 'Asia/Brunei',
                'default_language' => Language::ENGLISH,
            ],
            'BO' => [
                'continent' => 'South America',
                'name' => 'Bolivia',
                'alpha3_code' => 'BOL',
                'dial_code' => '+591',
                'default_timezone' => 'America/La_Paz',
                'default_language' => Language::SPANISH,
            ],
            'BQ' => [
                'continent' => 'North America',
                'name' => 'Bonaire',
                'alpha3_code' => 'BES',
                'dial_code' => '+599',
                'default_timezone' => 'America/Kralendijk',
                'default_language' => Language::ENGLISH,
            ],
            'BR' => [
                'continent' => 'South America',
                'name' => 'Brazil',
                'alpha3_code' => 'BRA',
                'dial_code' => '+55',
                'default_currency_code' => Currency::BRL,
                'default_timezone' => 'America/Sao_Paulo',
                'default_language' => 'pt',
            ],
            'BS' => [
                'continent' => 'North America',
                'name' => 'Bahamas',
                'alpha3_code' => 'BHS',
                'dial_code' => '+1242',
                'default_timezone' => 'America/Nassau',
                'default_language' => Language::ENGLISH,
            ],
            'BT' => [
                'continent' => 'Asia',
                'name' => 'Bhutan',
                'alpha3_code' => 'BTN',
                'dial_code' => '+975',
                'default_timezone' => 'Asia/Thimphu',
                'default_language' => Language::ENGLISH,
            ],
            'BV' => [
                'continent' => 'Antarctica',
                'name' => 'Bouvet Island',
                'alpha3_code' => 'BVT',
                'dial_code' => '+47',
                'default_timezone' => 'Europe/Oslo',
                'default_language' => Language::ENGLISH,
            ],
            'BW' => [
                'continent' => 'Africa',
                'name' => 'Botswana',
                'alpha3_code' => 'BWA',
                'dial_code' => '+267',
                'default_timezone' => 'Africa/Gaborone',
                'default_language' => Language::ENGLISH,
            ],
            'BY' => [
                'continent' => 'Europe',
                'name' => 'Belarus',
                'alpha3_code' => 'BLR',
                'dial_code' => '+375',
                'default_timezone' => 'Europe/Minsk',
                'default_language' => Language::ENGLISH,
            ],
            'BZ' => [
                'continent' => 'North America',
                'name' => 'Belize',
                'alpha3_code' => 'BLZ',
                'dial_code' => '+501',
                'default_timezone' => 'America/Belize',
                'default_language' => Language::SPANISH,
            ],
            'CA' => [
                'continent' => 'North America',
                'name' => 'Canada',
                'alpha3_code' => 'CAN',
                'dial_code' => '+1',
                'default_currency_code' => Currency::CAD,
                'default_timezone' => 'America/Toronto',
                'default_language' => Language::ENGLISH,
            ],
            'CC' => [
                'continent' => 'Asia',
                'name' => 'Cocos (Keeling) Islands',
                'alpha3_code' => 'CCK',
                'dial_code' => '+61',
                'default_timezone' => 'Indian/Cocos',
                'default_language' => Language::ENGLISH,
            ],
            'CD' => [
                'continent' => 'Africa',
                'name' => 'Democratic Republic of the Congo',
                'alpha3_code' => 'COD',
                'dial_code' => '+243',
                'default_timezone' => 'Africa/Kinshasa',
                'default_language' => Language::ENGLISH,
            ],
            'CF' => [
                'continent' => 'Africa',
                'name' => 'Central African Republic',
                'alpha3_code' => 'CAF',
                'dial_code' => '+236',
                'default_timezone' => 'Africa/Bangui',
                'default_language' => Language::ENGLISH,
            ],
            'CG' => [
                'continent' => 'Africa',
                'name' => 'Republic of the Congo',
                'alpha3_code' => 'COG',
                'dial_code' => '+242',
                'default_timezone' => 'Africa/Brazzaville',
                'default_language' => Language::ENGLISH,
            ],
            'CH' => [
                'continent' => 'Europe',
                'name' => 'Switzerland',
                'alpha3_code' => 'CHE',
                'dial_code' => '+41',
                'default_currency_code' => Currency::CHF,
                'default_timezone' => 'Europe/Zurich',
                'default_language' => Language::FRENCH,
            ],
            'CI' => [
                'continent' => 'Africa',
                'name' => 'Ivory Coast',
                'alpha3_code' => 'CIV',
                'dial_code' => '+225',
                'default_timezone' => 'Africa/Abidjan',
                'default_language' => Language::FRENCH,
            ],
            'CK' => [
                'continent' => 'Oceania',
                'name' => 'Cook Islands',
                'alpha3_code' => 'COK',
                'dial_code' => '+682',
                'default_timezone' => 'Pacific/Rarotonga',
                'default_language' => Language::ENGLISH,
            ],
            'CL' => [
                'continent' => 'South America',
                'name' => 'Chile',
                'alpha3_code' => 'CHL',
                'dial_code' => '+56',
                'default_currency_code' => Currency::CLP,
                'default_timezone' => 'America/Santiago',
                'default_language' => Language::SPANISH,
            ],
            'CM' => [
                'continent' => 'Africa',
                'name' => 'Cameroon',
                'alpha3_code' => 'CMR',
                'dial_code' => '+237',
                'default_timezone' => 'Africa/Douala',
                'default_language' => Language::FRENCH,
            ],
            'CN' => [
                'continent' => 'Asia',
                'name' => 'China',
                'alpha3_code' => 'CHN',
                'dial_code' => '+86',
                'default_currency_code' => Currency::CNY,
                'default_timezone' => 'Asia/Shanghai',
                'default_language' => Language::CHINESE,
            ],
            'CO' => [
                'continent' => 'South America',
                'name' => 'Colombia',
                'alpha3_code' => 'COL',
                'dial_code' => '+57',
                'default_timezone' => 'America/Bogota',
                'default_language' => Language::SPANISH,
            ],
            'CR' => [
                'continent' => 'North America',
                'name' => 'Costa Rica',
                'alpha3_code' => 'CRI',
                'dial_code' => '+506',
                'default_timezone' => 'America/Costa_Rica',
                'default_language' => Language::SPANISH,
            ],
            'CU' => [
                'continent' => 'North America',
                'name' => 'Cuba',
                'alpha3_code' => 'CUB',
                'dial_code' => '+53',
                'default_timezone' => 'America/Havana',
                'default_language' => Language::SPANISH,
            ],
            'CV' => [
                'continent' => 'Africa',
                'name' => 'Cape Verde',
                'alpha3_code' => 'CPV',
                'dial_code' => '+238',
                'default_timezone' => 'Atlantic/Cape_Verde',
                'default_language' => 'pt',
            ],
            'CW' => [
                'continent' => 'North America',
                'name' => 'Curaçao',
                'alpha3_code' => 'CUW',
                'dial_code' => '+599',
                'default_timezone' => 'America/Curacao',
                'default_language' => Language::ENGLISH,
            ],
            'CX' => [
                'continent' => 'Oceania',
                'name' => 'Christmas Island',
                'alpha3_code' => 'CXR',
                'dial_code' => '+61',
                'default_timezone' => 'Indian/Christmas',
                'default_language' => Language::ENGLISH,
            ],
            'CY' => [
                'continent' => 'Europe',
                'name' => 'Cyprus',
                'alpha3_code' => 'CYP',
                'dial_code' => '+357',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Asia/Nicosia',
                'default_language' => Language::ENGLISH,
            ],
            'CZ' => [
                'continent' => 'Europe',
                'name' => 'Czechia',
                'alpha3_code' => 'CZE',
                'dial_code' => '+420',
                'default_currency_code' => Currency::CZK,
                'default_timezone' => 'Europe/Prague',
                'default_language' => Language::ENGLISH,
            ],
            'DE' => [
                'continent' => 'Europe',
                'name' => 'Germany',
                'alpha3_code' => 'DEU',
                'dial_code' => '+49',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Berlin',
                'default_language' => Language::GERMAN,
            ],
            'DJ' => [
                'continent' => 'Africa',
                'name' => 'Djibouti',
                'alpha3_code' => 'DJI',
                'dial_code' => '+253',
                'default_timezone' => 'Africa/Djibouti',
                'default_language' => Language::FRENCH,
            ],
            'DK' => [
                'continent' => 'Europe',
                'name' => 'Denmark',
                'alpha3_code' => 'DNK',
                'dial_code' => '+45',
                'default_currency_code' => Currency::DKK,
                'default_timezone' => 'Europe/Copenhagen',
                'default_language' => Language::ENGLISH,
            ],
            'DM' => [
                'continent' => 'North America',
                'name' => 'Dominica',
                'alpha3_code' => 'DMA',
                'dial_code' => '+1767',
                'default_timezone' => 'America/Dominica',
                'default_language' => Language::SPANISH,
            ],
            'DO' => [
                'continent' => 'North America',
                'name' => 'Dominican Republic',
                'alpha3_code' => 'DOM',
                'dial_code' => '+1809',
                'default_timezone' => 'America/Santo_Domingo',
                'default_language' => Language::SPANISH,
            ],
            'DZ' => [
                'continent' => 'Africa',
                'name' => 'Algeria',
                'alpha3_code' => 'DZA',
                'dial_code' => '+213',
                'default_timezone' => 'Africa/Algiers',
                'default_language' => Language::ENGLISH,
            ],
            'EC' => [
                'continent' => 'South America',
                'name' => 'Ecuador',
                'alpha3_code' => 'ECU',
                'dial_code' => '+593',
                'default_timezone' => 'America/Guayaquil',
                'default_language' => Language::SPANISH,
            ],
            'EE' => [
                'continent' => 'Europe',
                'name' => 'Estonia',
                'alpha3_code' => 'EST',
                'dial_code' => '+372',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Tallinn',
                'default_language' => Language::ENGLISH,
            ],
            'EG' => [
                'continent' => 'Africa',
                'name' => 'Egypt',
                'alpha3_code' => 'EGY',
                'dial_code' => '+20',
                'default_timezone' => 'Africa/Cairo',
                'default_language' => Language::ENGLISH,
            ],
            'EH' => [
                'continent' => 'Africa',
                'name' => 'Western Sahara',
                'alpha3_code' => 'ESH',
                'dial_code' => '+212',
                'default_timezone' => 'Africa/El_Aaiun',
                'default_language' => Language::ENGLISH,
            ],
            'ER' => [
                'continent' => 'Africa',
                'name' => 'Eritrea',
                'alpha3_code' => 'ERI',
                'dial_code' => '+291',
                'default_timezone' => 'Africa/Asmara',
                'default_language' => Language::ENGLISH,
            ],
            'ES' => [
                'continent' => 'Europe',
                'name' => 'Spain',
                'alpha3_code' => 'ESP',
                'dial_code' => '+34',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Madrid',
                'default_language' => Language::SPANISH,
            ],
            'ET' => [
                'continent' => 'Africa',
                'name' => 'Ethiopia',
                'alpha3_code' => 'ETH',
                'dial_code' => '+251',
                'default_timezone' => 'Africa/Addis_Ababa',
                'default_language' => Language::ENGLISH,
            ],
            'FI' => [
                'continent' => 'Europe',
                'name' => 'Finland',
                'alpha3_code' => 'FIN',
                'dial_code' => '+358',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Helsinki',
                'default_language' => Language::ENGLISH,
            ],
            'FJ' => [
                'continent' => 'Oceania',
                'name' => 'Fiji',
                'alpha3_code' => 'FJI',
                'dial_code' => '+679',
                'default_timezone' => 'Pacific/Fiji',
                'default_language' => Language::ENGLISH,
            ],
            'FK' => [
                'continent' => 'South America',
                'name' => 'Falkland Islands',
                'alpha3_code' => 'FLK',
                'dial_code' => '+500',
                'default_timezone' => 'Atlantic/Stanley',
                'default_language' => Language::ENGLISH,
            ],
            'FM' => [
                'continent' => 'Oceania',
                'name' => 'Micronesia',
                'alpha3_code' => 'FSM',
                'dial_code' => '+691',
                'default_timezone' => 'Pacific/Kosrae',
                'default_language' => Language::ENGLISH,
            ],
            'FO' => [
                'continent' => 'Europe',
                'name' => 'Faroe Islands',
                'alpha3_code' => 'FRO',
                'dial_code' => '+298',
                'default_timezone' => 'Atlantic/Faroe',
                'default_language' => Language::ENGLISH,
            ],
            'FR' => [
                'continent' => 'Europe',
                'name' => 'France',
                'alpha3_code' => 'FRA',
                'dial_code' => '+33',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Paris',
                'default_language' => Language::FRENCH,
            ],
            'GA' => [
                'continent' => 'Africa',
                'name' => 'Gabon',
                'alpha3_code' => 'GAB',
                'dial_code' => '+241',
                'default_timezone' => 'Africa/Libreville',
                'default_language' => Language::FRENCH,
            ],
            'GB' => [
                'continent' => 'Europe',
                'name' => 'United Kingdom',
                'alpha3_code' => 'GBR',
                'dial_code' => '+44',
                'default_currency_code' => Currency::GBP,
                'default_timezone' => 'Europe/London',
                'default_language' => Language::ENGLISH,
            ],
            'GD' => [
                'continent' => 'North America',
                'name' => 'Grenada',
                'alpha3_code' => 'GRD',
                'dial_code' => '+1473',
                'default_timezone' => 'America/Grenada',
                'default_language' => Language::SPANISH,
            ],
            'GE' => [
                'continent' => 'Asia',
                'name' => 'Georgia',
                'alpha3_code' => 'GEO',
                'dial_code' => '+995',
                'default_timezone' => 'Asia/Tbilisi',
                'default_language' => Language::ENGLISH,
            ],
            'GF' => [
                'continent' => 'South America',
                'name' => 'French Guiana',
                'alpha3_code' => 'GUF',
                'dial_code' => '+594',
                'default_timezone' => 'America/Cayenne',
                'default_language' => Language::FRENCH,
            ],
            'GG' => [
                'continent' => 'Europe',
                'name' => 'Guernsey',
                'alpha3_code' => 'GGY',
                'dial_code' => '+44',
                'default_timezone' => 'Europe/Guernsey',
                'default_language' => Language::ENGLISH,
            ],
            'GH' => [
                'continent' => 'Africa',
                'name' => 'Ghana',
                'alpha3_code' => 'GHA',
                'dial_code' => '+233',
                'default_timezone' => 'Africa/Accra',
                'default_language' => Language::ENGLISH,
            ],
            'GI' => [
                'continent' => 'Europe',
                'name' => 'Gibraltar',
                'alpha3_code' => 'GIB',
                'dial_code' => '+350',
                'default_timezone' => 'Europe/Gibraltar',
                'default_language' => Language::ENGLISH,
            ],
            'GL' => [
                'continent' => 'North America',
                'name' => 'Greenland',
                'alpha3_code' => 'GRL',
                'dial_code' => '+299',
                'default_currency_code' => Currency::DKK,
                'default_timezone' => 'America/Nuuk',
                'default_language' => Language::ENGLISH,
            ],
            'GM' => [
                'continent' => 'Africa',
                'name' => 'Gambia',
                'alpha3_code' => 'GMB',
                'dial_code' => '+220',
                'default_timezone' => 'Africa/Banjul',
                'default_language' => Language::ENGLISH,
            ],
            'GN' => [
                'continent' => 'Africa',
                'name' => 'Guinea',
                'alpha3_code' => 'GIN',
                'dial_code' => '+224',
                'default_timezone' => 'Africa/Conakry',
                'default_language' => Language::FRENCH,
            ],
            'GP' => [
                'continent' => 'North America',
                'name' => 'Guadeloupe',
                'alpha3_code' => 'GLP',
                'dial_code' => '+590',
                'default_timezone' => 'America/Guadeloupe',
                'default_language' => Language::FRENCH,
            ],
            'GQ' => [
                'continent' => 'Africa',
                'name' => 'Equatorial Guinea',
                'alpha3_code' => 'GNQ',
                'dial_code' => '+240',
                'default_timezone' => 'Africa/Malabo',
                'default_language' => Language::SPANISH,
            ],
            'GR' => [
                'continent' => 'Europe',
                'name' => 'Greece',
                'alpha3_code' => 'GRC',
                'dial_code' => '+30',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Athens',
                'default_language' => Language::ENGLISH,
            ],
            'GS' => [
                'continent' => 'Antarctica',
                'name' => 'South Georgia and the South Sandwich Islands',
                'alpha3_code' => 'SGS',
                'dial_code' => '+500',
                'default_timezone' => 'Atlantic/South_Georgia',
                'default_language' => Language::ENGLISH,
            ],
            'GT' => [
                'continent' => 'North America',
                'name' => 'Guatemala',
                'alpha3_code' => 'GTM',
                'dial_code' => '+502',
                'default_timezone' => 'America/Guatemala',
                'default_language' => Language::SPANISH,
            ],
            'GU' => [
                'continent' => 'Oceania',
                'name' => 'Guam',
                'alpha3_code' => 'GUM',
                'dial_code' => '+1671',
                'default_timezone' => 'Pacific/Guam',
                'default_language' => Language::ENGLISH,
            ],
            'GW' => [
                'continent' => 'Africa',
                'name' => 'Guinea-Bissau',
                'alpha3_code' => 'GNB',
                'dial_code' => '+245',
                'default_timezone' => 'Africa/Bissau',
                'default_language' => Language::PORTUGUESE,
            ],
            'GY' => [
                'continent' => 'South America',
                'name' => 'Guyana',
                'alpha3_code' => 'GUY',
                'dial_code' => '+592',
                'default_timezone' => 'America/Guyana',
                'default_language' => Language::ENGLISH,
            ],
            'HK' => [
                'continent' => 'Asia',
                'name' => 'Hong Kong',
                'alpha3_code' => 'HKG',
                'dial_code' => '+852',
                'default_currency_code' => Currency::HKD,
                'default_timezone' => 'Asia/Hong_Kong',
                'default_language' => Language::ENGLISH,
            ],
            'HM' => [
                'continent' => 'Antarctica',
                'name' => 'Heard Island and McDonald Islands',
                'alpha3_code' => 'HMD',
                'dial_code' => '+6723',
                'default_timezone' => 'Australia/Perth',
                'default_language' => Language::ENGLISH,
            ],
            'HN' => [
                'continent' => 'North America',
                'name' => 'Honduras',
                'alpha3_code' => 'HND',
                'dial_code' => '+504',
                'default_timezone' => 'America/Tegucigalpa',
                'default_language' => Language::SPANISH,
            ],
            'HR' => [
                'continent' => 'Europe',
                'name' => 'Croatia',
                'alpha3_code' => 'HRV',
                'dial_code' => '+385',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Zagreb',
                'default_language' => Language::ENGLISH,
            ],
            'HT' => [
                'continent' => 'North America',
                'name' => 'Haiti',
                'alpha3_code' => 'HTI',
                'dial_code' => '+509',
                'default_timezone' => 'America/Port-au-Prince',
                'default_language' => Language::FRENCH,
            ],
            'HU' => [
                'continent' => 'Europe',
                'name' => 'Hungary',
                'alpha3_code' => 'HUN',
                'dial_code' => '+36',
                'default_timezone' => 'Europe/Budapest',
                'default_language' => Language::ENGLISH,
            ],
            'ID' => [
                'continent' => 'Asia',
                'name' => 'Indonesia',
                'alpha3_code' => 'IDN',
                'dial_code' => '+62',
                'default_currency_code' => Currency::IDR,
                'default_timezone' => 'Asia/Jakarta',
                'default_language' => Language::ENGLISH,
            ],
            'IE' => [
                'continent' => 'Europe',
                'name' => 'Ireland',
                'alpha3_code' => 'IRL',
                'dial_code' => '+353',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Dublin',
                'default_language' => Language::ENGLISH,
            ],
            'IL' => [
                'continent' => 'Asia',
                'name' => 'Israel',
                'alpha3_code' => 'ISR',
                'dial_code' => '+972',
                'default_currency_code' => Currency::ILS,
                'default_timezone' => 'Asia/Jerusalem',
                'default_language' => Language::ENGLISH,
            ],
            'IM' => [
                'continent' => 'Europe',
                'name' => 'Isle of Man',
                'alpha3_code' => 'IMN',
                'dial_code' => '+44',
                'default_timezone' => 'Europe/Isle_of_Man',
                'default_language' => Language::ENGLISH,
            ],
            'IN' => [
                'continent' => 'Asia',
                'name' => 'India',
                'alpha3_code' => 'IND',
                'dial_code' => '+91',
                'default_currency_code' => Currency::INR,
                'default_timezone' => 'Asia/Kolkata',
                'default_language' => Language::ENGLISH,
            ],
            'IO' => [
                'continent' => 'Asia',
                'name' => 'British Indian Ocean Territory',
                'alpha3_code' => 'IOT',
                'dial_code' => '+246',
                'default_timezone' => 'Indian/Chagos',
                'default_language' => Language::ENGLISH,
            ],
            'IQ' => [
                'continent' => 'Asia',
                'name' => 'Iraq',
                'alpha3_code' => 'IRQ',
                'dial_code' => '+964',
                'default_timezone' => 'Asia/Baghdad',
                'default_language' => Language::ENGLISH,
            ],
            'IR' => [
                'continent' => 'Asia',
                'name' => 'Iran',
                'alpha3_code' => 'IRN',
                'dial_code' => '+98',
                'default_timezone' => 'Asia/Tehran',
                'default_language' => Language::ENGLISH,
            ],
            'IS' => [
                'continent' => 'Europe',
                'name' => 'Iceland',
                'alpha3_code' => 'ISL',
                'dial_code' => '+354',
                'default_timezone' => 'Atlantic/Reykjavik',
                'default_language' => Language::ENGLISH,
            ],
            'IT' => [
                'continent' => 'Europe',
                'name' => 'Italy',
                'alpha3_code' => 'ITA',
                'dial_code' => '+39',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Rome',
                'default_language' => Language::ITALIAN,
            ],
            'JE' => [
                'continent' => 'Europe',
                'name' => 'Jersey',
                'alpha3_code' => 'JEY',
                'dial_code' => '+44',
                'default_timezone' => 'Europe/Jersey',
                'default_language' => Language::ENGLISH,
            ],
            'JM' => [
                'continent' => 'North America',
                'name' => 'Jamaica',
                'alpha3_code' => 'JAM',
                'dial_code' => '+1876',
                'default_timezone' => 'America/Jamaica',
                'default_language' => Language::ENGLISH,
            ],
            'JO' => [
                'continent' => 'Asia',
                'name' => 'Jordan',
                'alpha3_code' => 'JOR',
                'dial_code' => '+962',
                'default_timezone' => 'Asia/Amman',
                'default_language' => Language::ENGLISH,
            ],
            'JP' => [
                'continent' => 'Asia',
                'name' => 'Japan',
                'alpha3_code' => 'JPN',
                'dial_code' => '+81',
                'default_currency_code' => Currency::JPY,
                'default_timezone' => 'Asia/Tokyo',
                'default_language' => Language::ENGLISH,
            ],
            'KE' => [
                'continent' => 'Africa',
                'name' => 'Kenya',
                'alpha3_code' => 'KEN',
                'dial_code' => '+254',
                'default_timezone' => 'Africa/Nairobi',
                'default_language' => Language::ENGLISH,
            ],
            'KG' => [
                'continent' => 'Asia',
                'name' => 'Kyrgyzstan',
                'alpha3_code' => 'KGZ',
                'dial_code' => '+996',
                'default_timezone' => 'Asia/Bishkek',
                'default_language' => Language::ENGLISH,
            ],
            'KH' => [
                'continent' => 'Asia',
                'name' => 'Cambodia',
                'alpha3_code' => 'KHM',
                'dial_code' => '+855',
                'default_timezone' => 'Asia/Phnom_Penh',
                'default_language' => Language::ENGLISH,
            ],
            'KI' => [
                'continent' => 'Oceania',
                'name' => 'Kiribati',
                'alpha3_code' => 'KIR',
                'dial_code' => '+686',
                'default_timezone' => 'Pacific/Tarawa',
                'default_language' => Language::ENGLISH,
            ],
            'KM' => [
                'continent' => 'Africa',
                'name' => 'Comoros',
                'alpha3_code' => 'COM',
                'dial_code' => '+269',
                'default_timezone' => 'Indian/Comoro',
                'default_language' => Language::FRENCH,
            ],
            'KN' => [
                'continent' => 'North America',
                'name' => 'Saint Kitts and Nevis',
                'alpha3_code' => 'KNA',
                'dial_code' => '+1869',
                'default_timezone' => 'America/St_Kitts',
                'default_language' => Language::ENGLISH,
            ],
            'KP' => [
                'continent' => 'Asia',
                'name' => 'North Korea',
                'alpha3_code' => 'PRK',
                'dial_code' => '+850',
                'default_timezone' => 'Asia/Pyongyang',
                'default_language' => Language::ENGLISH,
            ],
            'KR' => [
                'continent' => 'Asia',
                'name' => 'South Korea',
                'alpha3_code' => 'KOR',
                'dial_code' => '+82',
                'default_currency_code' => Currency::KRW,
                'default_timezone' => 'Asia/Seoul',
                'default_language' => Language::ENGLISH,
            ],
            'KW' => [
                'continent' => 'Asia',
                'name' => 'Kuwait',
                'alpha3_code' => 'KWT',
                'dial_code' => '+965',
                'default_timezone' => 'Asia/Kuwait',
                'default_language' => Language::ENGLISH,
            ],
            'KY' => [
                'continent' => 'North America',
                'name' => 'Cayman Islands',
                'alpha3_code' => 'CYM',
                'dial_code' => '+1345',
                'default_timezone' => 'America/Cayman',
                'default_language' => Language::ENGLISH,
            ],
            'KZ' => [
                'continent' => 'Asia',
                'name' => 'Kazakhstan',
                'alpha3_code' => 'KAZ',
                'dial_code' => '+7',
                'default_timezone' => 'Asia/Almaty',
                'default_language' => Language::ENGLISH,
            ],
            'LA' => [
                'continent' => 'Asia',
                'name' => 'Laos',
                'alpha3_code' => 'LAO',
                'dial_code' => '+856',
                'default_timezone' => 'Asia/Vientiane',
                'default_language' => Language::ENGLISH,
            ],
            'LB' => [
                'continent' => 'Asia',
                'name' => 'Lebanon',
                'alpha3_code' => 'LBN',
                'dial_code' => '+961',
                'default_timezone' => 'Asia/Beirut',
                'default_language' => Language::ENGLISH,
            ],
            'LC' => [
                'continent' => 'North America',
                'name' => 'Saint Lucia',
                'alpha3_code' => 'LCA',
                'dial_code' => '+1758',
                'default_timezone' => 'America/St_Lucia',
                'default_language' => Language::ENGLISH,
            ],
            'LI' => [
                'continent' => 'Europe',
                'name' => 'Liechtenstein',
                'alpha3_code' => 'LIE',
                'dial_code' => '+423',
                'default_currency_code' => Currency::CHF,
                'default_timezone' => 'Europe/Vaduz',
                'default_language' => Language::FRENCH,
            ],
            'LK' => [
                'continent' => 'Asia',
                'name' => 'Sri Lanka',
                'alpha3_code' => 'LKA',
                'dial_code' => '+94',
                'default_timezone' => 'Asia/Colombo',
                'default_language' => Language::ENGLISH,
            ],
            'LR' => [
                'continent' => 'Africa',
                'name' => 'Liberia',
                'alpha3_code' => 'LBR',
                'dial_code' => '+231',
                'default_timezone' => 'Africa/Monrovia',
                'default_language' => Language::ENGLISH,
            ],
            'LS' => [
                'continent' => 'Africa',
                'name' => 'Lesotho',
                'alpha3_code' => 'LSO',
                'dial_code' => '+266',
                'default_timezone' => 'Africa/Maseru',
                'default_language' => Language::ENGLISH,
            ],
            'LT' => [
                'continent' => 'Europe',
                'name' => 'Lithuania',
                'alpha3_code' => 'LTU',
                'dial_code' => '+370',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Vilnius',
                'default_language' => Language::ENGLISH,
            ],
            'LU' => [
                'continent' => 'Europe',
                'name' => 'Luxembourg',
                'alpha3_code' => 'LUX',
                'dial_code' => '+352',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Luxembourg',
                'default_language' => Language::FRENCH,
            ],
            'LV' => [
                'continent' => 'Europe',
                'name' => 'Latvia',
                'alpha3_code' => 'LVA',
                'dial_code' => '+371',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Riga',
                'default_language' => Language::ENGLISH,
            ],
            'LY' => [
                'continent' => 'Africa',
                'name' => 'Libya',
                'alpha3_code' => 'LBY',
                'dial_code' => '+218',
                'default_timezone' => 'Africa/Tripoli',
                'default_language' => Language::ENGLISH,
            ],
            'MA' => [
                'continent' => 'Africa',
                'name' => 'Morocco',
                'alpha3_code' => 'MAR',
                'dial_code' => '+212',
                'default_timezone' => 'Africa/Casablanca',
                'default_language' => Language::FRENCH,
            ],
            'MC' => [
                'continent' => 'Europe',
                'name' => 'Monaco',
                'alpha3_code' => 'MCO',
                'dial_code' => '+377',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Monaco',
                'default_language' => Language::FRENCH,
            ],
            'MD' => [
                'continent' => 'Europe',
                'name' => 'Moldova',
                'alpha3_code' => 'MDA',
                'dial_code' => '+373',
                'default_timezone' => 'Europe/Chisinau',
                'default_language' => Language::ENGLISH,
            ],
            'ME' => [
                'continent' => 'Europe',
                'name' => 'Montenegro',
                'alpha3_code' => 'MNE',
                'dial_code' => '+382',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Podgorica',
                'default_language' => Language::ENGLISH,
            ],
            'MF' => [
                'continent' => 'North America',
                'name' => 'Saint Martin',
                'alpha3_code' => 'MAF',
                'dial_code' => '+1599',
                'default_timezone' => 'America/Marigot',
                'default_language' => Language::ENGLISH,
            ],
            'MG' => [
                'continent' => 'Africa',
                'name' => 'Madagascar',
                'alpha3_code' => 'MDG',
                'dial_code' => '+261',
                'default_timezone' => 'Indian/Antananarivo',
                'default_language' => Language::FRENCH,
            ],
            'MH' => [
                'continent' => 'Oceania',
                'name' => 'Marshall Islands',
                'alpha3_code' => 'MHL',
                'dial_code' => '+692',
                'default_timezone' => 'Pacific/Majuro',
                'default_language' => Language::ENGLISH,
            ],
            'MK' => [
                'continent' => 'Europe',
                'name' => 'Macedonia',
                'alpha3_code' => 'MKD',
                'dial_code' => '+389',
                'default_timezone' => 'Europe/Skopje',
                'default_language' => Language::ENGLISH,
            ],
            'ML' => [
                'continent' => 'Africa',
                'name' => 'Mali',
                'alpha3_code' => 'MLI',
                'dial_code' => '+223',
                'default_timezone' => 'Africa/Bamako',
                'default_language' => Language::FRENCH,
            ],
            'MM' => [
                'continent' => 'Asia',
                'name' => 'Myanmar',
                'alpha3_code' => 'MMR',
                'dial_code' => '+95',
                'default_timezone' => 'Asia/Yangon',
                'default_language' => Language::ENGLISH,
            ],
            'MN' => [
                'continent' => 'Asia',
                'name' => 'Mongolia',
                'alpha3_code' => 'MNG',
                'dial_code' => '+976',
                'default_timezone' => 'Asia/Ulaanbaatar',
                'default_language' => Language::ENGLISH,
            ],
            'MO' => [
                'continent' => 'Asia',
                'name' => 'Macao',
                'alpha3_code' => 'MAC',
                'dial_code' => '+853',
                'default_timezone' => 'Asia/Macau',
                'default_language' => Language::PORTUGUESE,
            ],
            'MP' => [
                'continent' => 'Oceania',
                'name' => 'Northern Mariana Islands',
                'alpha3_code' => 'MNP',
                'dial_code' => '+1670',
                'default_timezone' => 'Pacific/Saipan',
                'default_language' => Language::ENGLISH,
            ],
            'MQ' => [
                'continent' => 'North America',
                'name' => 'Martinique',
                'alpha3_code' => 'MTQ',
                'dial_code' => '+596',
                'default_timezone' => 'America/Martinique',
                'default_language' => Language::FRENCH,
            ],
            'MR' => [
                'continent' => 'Africa',
                'name' => 'Mauritania',
                'alpha3_code' => 'MRT',
                'dial_code' => '+222',
                'default_timezone' => 'Africa/Nouakchott',
                'default_language' => Language::ENGLISH,
            ],
            'MS' => [
                'continent' => 'North America',
                'name' => 'Montserrat',
                'alpha3_code' => 'MSR',
                'dial_code' => '+1664',
                'default_timezone' => 'America/Montserrat',
                'default_language' => Language::ENGLISH,
            ],
            'MT' => [
                'continent' => 'Europe',
                'name' => 'Malta',
                'alpha3_code' => 'MLT',
                'dial_code' => '+356',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Malta',
                'default_language' => Language::ENGLISH,
            ],
            'MU' => [
                'continent' => 'Africa',
                'name' => 'Mauritius',
                'alpha3_code' => 'MUS',
                'dial_code' => '+230',
                'default_timezone' => 'Indian/Mauritius',
                'default_language' => Language::ENGLISH,
            ],
            'MV' => [
                'continent' => 'Asia',
                'name' => 'Maldives',
                'alpha3_code' => 'MDV',
                'dial_code' => '+960',
                'default_timezone' => 'Indian/Maldives',
                'default_language' => Language::ENGLISH,
            ],
            'MW' => [
                'continent' => 'Africa',
                'name' => 'Malawi',
                'alpha3_code' => 'MWI',
                'dial_code' => '+265',
                'default_timezone' => 'Africa/Blantyre',
                'default_language' => Language::ENGLISH,
            ],
            'MX' => [
                'continent' => 'North America',
                'name' => 'Mexico',
                'alpha3_code' => 'MEX',
                'dial_code' => '+52',
                'default_currency_code' => Currency::MXN,
                'default_timezone' => 'America/Mexico_City',
                'default_language' => Language::SPANISH,
            ],
            'MY' => [
                'continent' => 'Asia',
                'name' => 'Malaysia',
                'alpha3_code' => 'MYS',
                'dial_code' => '+60',
                'default_currency_code' => Currency::MYR,
                'default_timezone' => 'Asia/Kuala_Lumpur',
                'default_language' => Language::ENGLISH,
            ],
            'MZ' => [
                'continent' => 'Africa',
                'name' => 'Mozambique',
                'alpha3_code' => 'MOZ',
                'dial_code' => '+258',
                'default_timezone' => 'Africa/Maputo',
                'default_language' => Language::PORTUGUESE,
            ],
            'NA' => [
                'continent' => 'Africa',
                'name' => 'Namibia',
                'alpha3_code' => 'NAM',
                'dial_code' => '+264',
                'default_timezone' => 'Africa/Windhoek',
                'default_language' => Language::ENGLISH,
            ],
            'NC' => [
                'continent' => 'Oceania',
                'name' => 'New Caledonia',
                'alpha3_code' => 'NCL',
                'dial_code' => '+687',
                'default_timezone' => 'Pacific/Noumea',
                'default_language' => Language::FRENCH,
            ],
            'NE' => [
                'continent' => 'Africa',
                'name' => 'Niger',
                'alpha3_code' => 'NER',
                'dial_code' => '+227',
                'default_timezone' => 'Africa/Niamey',
                'default_language' => Language::FRENCH,
            ],
            'NF' => [
                'continent' => 'Oceania',
                'name' => 'Norfolk Island',
                'alpha3_code' => 'NFK',
                'dial_code' => '+672',
                'default_timezone' => 'Pacific/Norfolk',
                'default_language' => Language::ENGLISH,
            ],
            'NG' => [
                'continent' => 'Africa',
                'name' => 'Nigeria',
                'alpha3_code' => 'NGA',
                'dial_code' => '+234',
                'default_timezone' => 'Africa/Lagos',
                'default_language' => Language::ENGLISH,
            ],
            'NI' => [
                'continent' => 'North America',
                'name' => 'Nicaragua',
                'alpha3_code' => 'NIC',
                'dial_code' => '+505',
                'default_timezone' => 'America/Managua',
                'default_language' => Language::SPANISH,
            ],
            'NL' => [
                'continent' => 'Europe',
                'name' => 'Netherlands',
                'alpha3_code' => 'NLD',
                'dial_code' => '+31',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Amsterdam',
                'default_language' => Language::ENGLISH,
            ],
            'NO' => [
                'continent' => 'Europe',
                'name' => 'Norway',
                'alpha3_code' => 'NOR',
                'dial_code' => '+47',
                'default_currency_code' => Currency::NOK,
                'default_timezone' => 'Europe/Oslo',
                'default_language' => Language::ENGLISH,
            ],
            'NP' => [
                'continent' => 'Asia',
                'name' => 'Nepal',
                'alpha3_code' => 'NPL',
                'dial_code' => '+977',
                'default_timezone' => 'Asia/Kathmandu',
                'default_language' => Language::ENGLISH,
            ],
            'NR' => [
                'continent' => 'Oceania',
                'name' => 'Nauru',
                'alpha3_code' => 'NRU',
                'dial_code' => '+674',
                'default_timezone' => 'Pacific/Nauru',
                'default_language' => Language::ENGLISH,
            ],
            'NU' => [
                'continent' => 'Oceania',
                'name' => 'Niue',
                'alpha3_code' => 'NIU',
                'dial_code' => '+683',
                'default_timezone' => 'Pacific/Niue',
                'default_language' => Language::ENGLISH,
            ],
            'NZ' => [
                'continent' => 'Oceania',
                'name' => 'New Zealand',
                'alpha3_code' => 'NZL',
                'dial_code' => '+64',
                'default_currency_code' => Currency::NZD,
                'default_timezone' => 'Pacific/Auckland',
                'default_language' => Language::ENGLISH,
            ],
            'OM' => [
                'continent' => 'Asia',
                'name' => 'Oman',
                'alpha3_code' => 'OMN',
                'dial_code' => '+968',
                'default_timezone' => 'Asia/Muscat',
                'default_language' => Language::ENGLISH,
            ],
            'PA' => [
                'continent' => 'North America',
                'name' => 'Panama',
                'alpha3_code' => 'PAN',
                'dial_code' => '+507',
                'default_timezone' => 'America/Panama',
                'default_language' => Language::SPANISH,
            ],
            'PE' => [
                'continent' => 'South America',
                'name' => 'Peru',
                'alpha3_code' => 'PER',
                'dial_code' => '+51',
                'default_timezone' => 'America/Lima',
                'default_language' => Language::SPANISH,
            ],
            'PF' => [
                'continent' => 'Oceania',
                'name' => 'French Polynesia',
                'alpha3_code' => 'PYF',
                'dial_code' => '+689',
                'default_timezone' => 'Pacific/Tahiti',
                'default_language' => Language::FRENCH,
            ],
            'PG' => [
                'continent' => 'Oceania',
                'name' => 'Papua New Guinea',
                'alpha3_code' => 'PNG',
                'dial_code' => '+675',
                'default_timezone' => 'Pacific/Port_Moresby',
                'default_language' => Language::ENGLISH,
            ],
            'PH' => [
                'continent' => 'Asia',
                'name' => 'Philippines',
                'alpha3_code' => 'PHL',
                'dial_code' => '+63',
                'default_currency_code' => Currency::PHP,
                'default_timezone' => 'Asia/Manila',
                'default_language' => Language::ENGLISH,
            ],
            'PK' => [
                'continent' => 'Asia',
                'name' => 'Pakistan',
                'alpha3_code' => 'PAK',
                'dial_code' => '+92',
                'default_timezone' => 'Asia/Karachi',
                'default_language' => Language::ENGLISH,
            ],
            'PL' => [
                'continent' => 'Europe',
                'name' => 'Poland',
                'alpha3_code' => 'POL',
                'dial_code' => '+48',
                'default_currency_code' => Currency::PLN,
                'default_timezone' => 'Europe/Warsaw',
                'default_language' => Language::ENGLISH,
            ],
            'PM' => [
                'continent' => 'North America',
                'name' => 'Saint Pierre and Miquelon',
                'alpha3_code' => 'SPM',
                'dial_code' => '+508',
                'default_timezone' => 'America/Miquelon',
                'default_language' => Language::FRENCH,
            ],
            'PN' => [
                'continent' => 'Oceania',
                'name' => 'Pitcairn Islands',
                'alpha3_code' => 'PCN',
                'dial_code' => '+870',
                'default_timezone' => 'Pacific/Pitcairn',
                'default_language' => Language::ENGLISH,
            ],
            'PR' => [
                'continent' => 'North America',
                'name' => 'Puerto Rico',
                'alpha3_code' => 'PRI',
                'dial_code' => '+1',
                'default_currency_code' => Currency::USD,
                'default_timezone' => 'America/Puerto_Rico',
                'default_language' => Language::ENGLISH,
            ],
            'PS' => [
                'continent' => 'Asia',
                'name' => 'Palestine',
                'alpha3_code' => 'PSE',
                'dial_code' => '+970',
                'default_timezone' => 'Asia/Gaza',
                'default_language' => Language::ENGLISH,
            ],
            'PT' => [
                'continent' => 'Europe',
                'name' => 'Portugal',
                'alpha3_code' => 'PRT',
                'dial_code' => '+351',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Lisbon',
                'default_language' => Language::PORTUGUESE,
            ],
            'PW' => [
                'continent' => 'Oceania',
                'name' => 'Palau',
                'alpha3_code' => 'PLW',
                'dial_code' => '+680',
                'default_timezone' => 'Pacific/Palau',
                'default_language' => Language::ENGLISH,
            ],
            'PY' => [
                'continent' => 'South America',
                'name' => 'Paraguay',
                'alpha3_code' => 'PRY',
                'dial_code' => '+595',
                'default_timezone' => 'America/Asuncion',
                'default_language' => Language::SPANISH,
            ],
            'QA' => [
                'continent' => 'Asia',
                'name' => 'Qatar',
                'alpha3_code' => 'QAT',
                'dial_code' => '+974',
                'default_timezone' => 'Asia/Qatar',
                'default_language' => Language::ENGLISH,
            ],
            'RE' => [
                'continent' => 'Africa',
                'name' => 'Réunion',
                'alpha3_code' => 'REU',
                'dial_code' => '+262',
                'default_timezone' => 'Indian/Reunion',
                'default_language' => Language::FRENCH,
            ],
            'RO' => [
                'continent' => 'Europe',
                'name' => 'Romania',
                'alpha3_code' => 'ROU',
                'dial_code' => '+40',
                'default_currency_code' => Currency::RON,
                'default_timezone' => 'Europe/Bucharest',
                'default_language' => Language::ENGLISH,
            ],
            'RS' => [
                'continent' => 'Europe',
                'name' => 'Serbia',
                'alpha3_code' => 'SRB',
                'dial_code' => '+381',
                'default_timezone' => 'Europe/Belgrade',
                'default_language' => Language::ENGLISH,
            ],
            'RU' => [
                'continent' => 'Europe',
                'name' => 'Russia',
                'alpha3_code' => 'RUS',
                'dial_code' => '+7',
                'default_currency_code' => Currency::RUB,
                'default_timezone' => 'Europe/Moscow',
                'default_language' => Language::ENGLISH,
            ],
            'RW' => [
                'continent' => 'Africa',
                'name' => 'Rwanda',
                'alpha3_code' => 'RWA',
                'dial_code' => '+250',
                'default_timezone' => 'Africa/Kigali',
                'default_language' => Language::ENGLISH,
            ],
            'SA' => [
                'continent' => 'Asia',
                'name' => 'Saudi Arabia',
                'alpha3_code' => 'SAU',
                'dial_code' => '+966',
                'default_currency_code' => Currency::SAR,
                'default_timezone' => 'Asia/Riyadh',
                'default_language' => Language::ENGLISH,
            ],
            'SB' => [
                'continent' => 'Oceania',
                'name' => 'Solomon Islands',
                'alpha3_code' => 'SLB',
                'dial_code' => '+677',
                'default_timezone' => 'Pacific/Guadalcanal',
                'default_language' => Language::ENGLISH,
            ],
            'SC' => [
                'continent' => 'Africa',
                'name' => 'Seychelles',
                'alpha3_code' => 'SYC',
                'dial_code' => '+248',
                'default_timezone' => 'Indian/Mahe',
                'default_language' => Language::ENGLISH,
            ],
            'SD' => [
                'continent' => 'Africa',
                'name' => 'Sudan',
                'alpha3_code' => 'SDN',
                'dial_code' => '+249',
                'default_timezone' => 'Africa/Khartoum',
                'default_language' => Language::ENGLISH,
            ],
            'SE' => [
                'continent' => 'Europe',
                'name' => 'Sweden',
                'alpha3_code' => 'SWE',
                'dial_code' => '+46',
                'default_currency_code' => Currency::SEK,
                'default_timezone' => 'Europe/Stockholm',
                'default_language' => Language::ENGLISH,
            ],
            'SG' => [
                'continent' => 'Asia',
                'name' => 'Singapore',
                'alpha3_code' => 'SGP',
                'dial_code' => '+65',
                'default_currency_code' => Currency::SGD,
                'default_timezone' => 'Asia/Singapore',
                'default_language' => Language::ENGLISH,
            ],
            'SH' => [
                'continent' => 'Africa',
                'name' => 'Saint Helena',
                'alpha3_code' => 'SHN',
                'dial_code' => '+290',
                'default_timezone' => 'Atlantic/St_Helena',
                'default_language' => Language::ENGLISH,
            ],
            'SI' => [
                'continent' => 'Europe',
                'name' => 'Slovenia',
                'alpha3_code' => 'SVN',
                'dial_code' => '+386',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Ljubljana',
                'default_language' => Language::ENGLISH,
            ],
            'SJ' => [
                'continent' => 'Europe',
                'name' => 'Svalbard and Jan Mayen',
                'alpha3_code' => 'SJM',
                'dial_code' => '+47',
                'default_currency_code' => Currency::NOK,
                'default_timezone' => 'Arctic/Longyearbyen',
                'default_language' => Language::ENGLISH,
            ],
            'SK' => [
                'continent' => 'Europe',
                'name' => 'Slovakia',
                'alpha3_code' => 'SVK',
                'dial_code' => '+421',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Bratislava',
                'default_language' => Language::ENGLISH,
            ],
            'SL' => [
                'continent' => 'Africa',
                'name' => 'Sierra Leone',
                'alpha3_code' => 'SLE',
                'dial_code' => '+232',
                'default_timezone' => 'Africa/Freetown',
                'default_language' => Language::ENGLISH,
            ],
            'SM' => [
                'continent' => 'Europe',
                'name' => 'San Marino',
                'alpha3_code' => 'SMR',
                'dial_code' => '+378',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/San_Marino',
                'default_language' => Language::ITALIAN,
            ],
            'SN' => [
                'continent' => 'Africa',
                'name' => 'Senegal',
                'alpha3_code' => 'SEN',
                'dial_code' => '+221',
                'default_timezone' => 'Africa/Dakar',
                'default_language' => Language::FRENCH,
            ],
            'SO' => [
                'continent' => 'Africa',
                'name' => 'Somalia',
                'alpha3_code' => 'SOM',
                'dial_code' => '+252',
                'default_timezone' => 'Africa/Mogadishu',
                'default_language' => Language::ENGLISH,
            ],
            'SR' => [
                'continent' => 'South America',
                'name' => 'Suriname',
                'alpha3_code' => 'SUR',
                'dial_code' => '+597',
                'default_timezone' => 'America/Paramaribo',
                'default_language' => Language::ENGLISH,
            ],
            'SS' => [
                'continent' => 'Africa',
                'name' => 'South Sudan',
                'alpha3_code' => 'SSD',
                'dial_code' => '+211',
                'default_timezone' => 'Africa/Juba',
                'default_language' => Language::ENGLISH,
            ],
            'ST' => [
                'continent' => 'Africa',
                'name' => 'São Tomé and Príncipe',
                'alpha3_code' => 'STP',
                'dial_code' => '+239',
                'default_timezone' => 'Africa/Sao_Tome',
                'default_language' => Language::PORTUGUESE,
            ],
            'SV' => [
                'continent' => 'North America',
                'name' => 'El Salvador',
                'alpha3_code' => 'SLV',
                'dial_code' => '+503',
                'default_timezone' => 'America/El_Salvador',
                'default_language' => Language::SPANISH,
            ],
            'SX' => [
                'continent' => 'North America',
                'name' => 'Sint Maarten',
                'alpha3_code' => 'SXM',
                'dial_code' => '+1',
                'default_timezone' => 'America/Lower_Princes',
                'default_language' => Language::ENGLISH,
            ],
            'SY' => [
                'continent' => 'Asia',
                'name' => 'Syria',
                'alpha3_code' => 'SYR',
                'dial_code' => '+963',
                'default_timezone' => 'Asia/Damascus',
                'default_language' => Language::ENGLISH,
            ],
            'SZ' => [
                'continent' => 'Africa',
                'name' => 'Swaziland',
                'alpha3_code' => 'SWZ',
                'dial_code' => '+268',
                'default_timezone' => 'Africa/Mbabane',
                'default_language' => Language::ENGLISH,
            ],
            'TC' => [
                'continent' => 'North America',
                'name' => 'Turks and Caicos Islands',
                'alpha3_code' => 'TCA',
                'dial_code' => '+1649',
                'default_timezone' => 'America/Grand_Turk',
                'default_language' => Language::ENGLISH,
            ],
            'TD' => [
                'continent' => 'Africa',
                'name' => 'Chad',
                'alpha3_code' => 'TCD',
                'dial_code' => '+235',
                'default_timezone' => 'Africa/Ndjamena',
                'default_language' => Language::ENGLISH,
            ],
            'TF' => [
                'continent' => 'Antarctica',
                'name' => 'French Southern Territories',
                'alpha3_code' => 'ATF',
                'dial_code' => '+262',
                'default_timezone' => 'Indian/Kerguelen',
                'default_language' => Language::FRENCH,
            ],
            'TG' => [
                'continent' => 'Africa',
                'name' => 'Togo',
                'alpha3_code' => 'TGO',
                'dial_code' => '+228',
                'default_timezone' => 'Africa/Lome',
                'default_language' => Language::FRENCH,
            ],
            'TH' => [
                'continent' => 'Asia',
                'name' => 'Thailand',
                'alpha3_code' => 'THA',
                'dial_code' => '+66',
                'default_currency_code' => Currency::THB,
                'default_timezone' => 'Asia/Bangkok',
                'default_language' => Language::ENGLISH,
            ],
            'TJ' => [
                'continent' => 'Asia',
                'name' => 'Tajikistan',
                'alpha3_code' => 'TJK',
                'dial_code' => '+992',
                'default_timezone' => 'Asia/Dushanbe',
                'default_language' => Language::ENGLISH,
            ],
            'TK' => [
                'continent' => 'Oceania',
                'name' => 'Tokelau',
                'alpha3_code' => 'TKL',
                'dial_code' => '+690',
                'default_timezone' => 'Pacific/Fakaofo',
                'default_language' => Language::ENGLISH,
            ],
            'TL' => [
                'continent' => 'Oceania',
                'name' => 'Timor-Leste',
                'alpha3_code' => 'TLS',
                'dial_code' => '+670',
                'default_timezone' => 'Asia/Dili',
                'default_language' => Language::ENGLISH,
            ],
            'TM' => [
                'continent' => 'Asia',
                'name' => 'Turkmenistan',
                'alpha3_code' => 'TKM',
                'dial_code' => '+993',
                'default_timezone' => 'Asia/Ashgabat',
                'default_language' => Language::ENGLISH,
            ],
            'TN' => [
                'continent' => 'Africa',
                'name' => 'Tunisia',
                'alpha3_code' => 'TUN',
                'dial_code' => '+216',
                'default_timezone' => 'Africa/Tunis',
                'default_language' => Language::ENGLISH,
            ],
            'TO' => [
                'continent' => 'Oceania',
                'name' => 'Tonga',
                'alpha3_code' => 'TON',
                'dial_code' => '+676',
                'default_timezone' => 'Pacific/Tongatapu',
                'default_language' => Language::ENGLISH,
            ],
            'TR' => [
                'continent' => 'Asia',
                'name' => 'Turkey',
                'alpha3_code' => 'TUR',
                'dial_code' => '+90',
                'default_currency_code' => Currency::TRY,
                'default_timezone' => 'Europe/Istanbul',
                'default_language' => Language::ENGLISH,
            ],
            'TT' => [
                'continent' => 'North America',
                'name' => 'Trinidad and Tobago',
                'alpha3_code' => 'TTO',
                'dial_code' => '+1868',
                'default_timezone' => 'America/Port_of_Spain',
                'default_language' => Language::ENGLISH,
            ],
            'TV' => [
                'continent' => 'Oceania',
                'name' => 'Tuvalu',
                'alpha3_code' => 'TUV',
                'dial_code' => '+688',
                'default_timezone' => 'Pacific/Funafuti',
                'default_language' => Language::ENGLISH,
            ],
            'TW' => [
                'continent' => 'Asia',
                'name' => 'Taiwan',
                'alpha3_code' => 'TWN',
                'dial_code' => '+886',
                'default_currency_code' => Currency::TWD,
                'default_timezone' => 'Asia/Taipei',
                'default_language' => Language::CHINESE,
            ],
            'TZ' => [
                'continent' => 'Africa',
                'name' => 'Tanzania',
                'alpha3_code' => 'TZA',
                'dial_code' => '+255',
                'default_timezone' => 'Africa/Dar_es_Salaam',
                'default_language' => Language::ENGLISH,
            ],
            'UA' => [
                'continent' => 'Europe',
                'name' => 'Ukraine',
                'alpha3_code' => 'UKR',
                'dial_code' => '+380',
                'default_currency_code' => Currency::UAH,
                'default_timezone' => 'Europe/Kyiv',
                'default_language' => Language::ENGLISH,
            ],
            'UG' => [
                'continent' => 'Africa',
                'name' => 'Uganda',
                'alpha3_code' => 'UGA',
                'dial_code' => '+256',
                'default_timezone' => 'Africa/Kampala',
                'default_language' => Language::ENGLISH,
            ],
            'UM' => [
                'continent' => 'Oceania',
                'name' => 'U.S. Minor Outlying Islands',
                'alpha3_code' => 'UMI',
                'dial_code' => '+1',
                'default_timezone' => 'Pacific/Wake',
                'default_language' => Language::ENGLISH,
            ],
            'US' => [
                'continent' => 'North America',
                'name' => 'United States',
                'alpha3_code' => 'USA',
                'dial_code' => '+1',
                'default_currency_code' => Currency::USD,
                'default_timezone' => 'America/New_York',
                'default_language' => Language::ENGLISH,
            ],
            'UY' => [
                'continent' => 'South America',
                'name' => 'Uruguay',
                'alpha3_code' => 'URY',
                'dial_code' => '+598',
                'default_currency_code' => Currency::UYU,
                'default_timezone' => 'America/Montevideo',
                'default_language' => Language::SPANISH,
            ],
            'UZ' => [
                'continent' => 'Asia',
                'name' => 'Uzbekistan',
                'alpha3_code' => 'UZB',
                'dial_code' => '+998',
                'default_timezone' => 'Asia/Tashkent',
                'default_language' => Language::ENGLISH,
            ],
            'VA' => [
                'continent' => 'Europe',
                'name' => 'Vatican City',
                'alpha3_code' => 'VAT',
                'dial_code' => '+379',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Vatican',
                'default_language' => Language::ITALIAN,
            ],
            'VC' => [
                'continent' => 'North America',
                'name' => 'Saint Vincent and the Grenadines',
                'alpha3_code' => 'VCT',
                'dial_code' => '+1784',
                'default_timezone' => 'America/St_Vincent',
                'default_language' => Language::ENGLISH,
            ],
            'VE' => [
                'continent' => 'South America',
                'name' => 'Venezuela',
                'alpha3_code' => 'VEN',
                'dial_code' => '+58',
                'default_timezone' => 'America/Caracas',
                'default_language' => Language::SPANISH,
            ],
            'VG' => [
                'continent' => 'North America',
                'name' => 'Virgin Islands (British)',
                'alpha3_code' => 'VGB',
                'dial_code' => '+1284',
                'default_timezone' => 'America/Tortola',
                'default_language' => Language::ENGLISH,
            ],
            'VI' => [
                'continent' => 'North America',
                'name' => 'Virgin Islands (U.S.)',
                'alpha3_code' => 'VIR',
                'dial_code' => '+1340',
                'default_timezone' => 'America/St_Thomas',
                'default_language' => Language::ENGLISH,
            ],
            'VN' => [
                'continent' => 'Asia',
                'name' => 'Viet Nam',
                'alpha3_code' => 'VNM',
                'dial_code' => '+84',
                'default_currency_code' => Currency::VND,
                'default_timezone' => 'Asia/Ho_Chi_Minh',
                'default_language' => Language::ENGLISH,
            ],
            'VU' => [
                'continent' => 'Oceania',
                'name' => 'Vanuatu',
                'alpha3_code' => 'VUT',
                'dial_code' => '+678',
                'default_timezone' => 'Pacific/Efate',
                'default_language' => Language::ENGLISH,
            ],
            'WF' => [
                'continent' => 'Oceania',
                'name' => 'Wallis and Futuna',
                'alpha3_code' => 'WLF',
                'dial_code' => '+681',
                'default_timezone' => 'Pacific/Wallis',
                'default_language' => Language::ENGLISH,
            ],
            'WS' => [
                'continent' => 'Oceania',
                'name' => 'Samoa',
                'alpha3_code' => 'WSM',
                'dial_code' => '+685',
                'default_timezone' => 'Pacific/Apia',
                'default_language' => Language::ENGLISH,
            ],
            'XK' => [
                'continent' => 'Europe',
                'name' => 'Kosovo',
                'alpha3_code' => 'XKX',
                'dial_code' => '+381',
                'default_currency_code' => Currency::EUR,
                'default_timezone' => 'Europe/Tirane',
                'default_language' => Language::ENGLISH,
            ],
            'YE' => [
                'continent' => 'Asia',
                'name' => 'Yemen',
                'alpha3_code' => 'YEM',
                'dial_code' => '+967',
                'default_timezone' => 'Asia/Aden',
                'default_language' => Language::ENGLISH,
            ],
            'YT' => [
                'continent' => 'Africa',
                'name' => 'Mayotte',
                'alpha3_code' => 'MYT',
                'dial_code' => '+262',
                'default_timezone' => 'Indian/Mayotte',
                'default_language' => Language::FRENCH,
            ],
            'ZA' => [
                'continent' => 'Africa',
                'name' => 'South Africa',
                'alpha3_code' => 'ZAF',
                'dial_code' => '+27',
                'default_currency_code' => Currency::ZAR,
                'default_timezone' => 'Africa/Johannesburg',
                'default_language' => Language::ENGLISH,
            ],
            'ZM' => [
                'continent' => 'Africa',
                'name' => 'Zambia',
                'alpha3_code' => 'ZMB',
                'dial_code' => '+260',
                'default_timezone' => 'Africa/Lusaka',
                'default_language' => Language::ENGLISH,
            ],
            'ZW' => [
                'continent' => 'Africa',
                'name' => 'Zimbabwe',
                'alpha3_code' => 'ZWE',
                'dial_code' => '+263',
                'default_timezone' => 'Africa/Harare',
                'default_language' => Language::ENGLISH,
            ],
        ];

    }
}
