<?php

namespace Macmotp\Countries\Support;

enum CountryCapital: string
{
    case ABUJA = 'Abuja'; // Nigeria
    case ABU_DHABI = 'Abu Dhabi'; // United Arab Emirates
    case ACCRA = 'Accra'; // Ghana
    case ADAMSTOWN = 'Adamstown'; // Pitcairn Islands
    case ADDIS_ABABA = 'Addis Ababa'; // Ethiopia
    case ALGIERS = 'Algiers'; // Algeria
    case ALOFI = 'Alofi'; // Niue
    case AMMAN = 'Amman'; // Jordan
    case AMSTERDAM = 'Amsterdam'; // Netherlands
    case ANDORRA_LA_VELLA = 'Andorra la Vella'; // Andorra
    case ANKARA = 'Ankara'; // Turkey
    case ANTANANARIVO = 'Antananarivo'; // Madagascar
    case APIA = 'Apia'; // Samoa
    case ASHGABAT = 'Ashgabat'; // Turkmenistan
    case ASMARA = 'Asmara'; // Eritrea
    case ASUNCION = 'Asunción'; // Paraguay
    case ATHENS = 'Athens'; // Greece
    case AVARUA = 'Avarua'; // Cook Islands
    case BAGHDAD = 'Baghdad'; // Iraq
    case BAKU = 'Baku'; // Azerbaijan
    case BAMAKO = 'Bamako'; // Mali
    case BANDAR_SERI_BEGAWAN = 'Bandar Seri Begawan'; // Brunei
    case BANGKOK = 'Bangkok'; // Thailand
    case BANGUI = 'Bangui'; // Central African Republic
    case BANJUL = 'Banjul'; // The Gambia
    case BASSETERRE = 'Basseterre'; // Saint Kitts and Nevis
    case BASSE_TERRE = 'Basse-Terre'; // Guadeloupe
    case BEIJING = 'Beijing'; // China
    case BEIRUT = 'Beirut'; // Lebanon
    case BELGRADE = 'Belgrade'; // Serbia
    case BELMOPAN = 'Belmopan'; // Belize
    case BERLIN = 'Berlin'; // Germany
    case BERN = 'Bern'; // Switzerland
    case BISHKEK = 'Bishkek'; // Kyrgyzstan
    case BISSAU = 'Bissau'; // Guinea-Bissau
    case BOGOTA = 'Bogotá'; // Colombia
    case BRASILIA = 'Brasília'; // Brazil
    case BRATISLAVA = 'Bratislava'; // Slovakia
    case BRAZZAVILLE = 'Brazzaville'; // Republic of the Congo
    case BRIDGETOWN = 'Bridgetown'; // Barbados
    case BRUSSELS = 'Brussels'; // Belgium
    case BUCHAREST = 'Bucharest'; // Romania
    case BUDAPEST = 'Budapest'; // Hungary
    case BUENOS_AIRES = 'Buenos Aires'; // Argentina
    case CAIRO = 'Cairo'; // Egypt
    case CANBERRA = 'Canberra'; // Australia
    case CARACAS = 'Caracas'; // Venezuela
    case CASTRIES = 'Castries'; // Saint Lucia
    case CAYENNE = 'Cayenne'; // French Guiana
    case CHARLOTTE_AMALIE = 'Charlotte Amalie'; // US Virgin Islands
    case CHISINAU = 'Chișinău'; // Moldova
    case COCKBURN_TOWN = 'Cockburn Town'; // Turks and Caicos Islands
    case COLOMBO = 'Colombo'; // Sri Lanka
    case CONAKRY = 'Conakry'; // Guinea
    case COPENHAGEN = 'Copenhagen'; // Denmark
    case DAKAR = 'Dakar'; // Senegal
    case DAMASCUS = 'Damascus'; // Syria
    case DHAKA = 'Dhaka'; // Bangladesh
    case DIEGO_GARCIA = 'Diego Garcia'; // British Indian Ocean Territory
    case DILI = 'Dili'; // East Timor
    case DJIBOUTI_CITY = 'Djibouti City'; // Djibouti
    case DODOMA = 'Dodoma'; // Tanzania
    case DOHA = 'Doha'; // Qatar
    case DOUGLAS = 'Douglas'; // Isle of Man
    case DUBLIN = 'Dublin'; // Ireland
    case DUSHANBE = 'Dushanbe'; // Tajikistan
    case EAST_JERUSALEM = 'East Jerusalem'; // Palestine
    case EL_AAIUN = 'El Aaiún'; // Western Sahara
    case FAKAOFO = 'Fakaofo'; // Tokelau
    case FLYING_FISH_COVE = 'Flying Fish Cove'; // Christmas Island
    case FORT_DE_FRANCE = 'Fort-de-France'; // Martinique
    case FREETOWN = 'Freetown'; // Sierra Leone
    case FUNAFUTI = 'Funafuti'; // Tuvalu
    case GABORONE = 'Gaborone'; // Botswana
    case GEORGETOWN = 'Georgetown'; // Guyana
    case GEORGE_TOWN = 'George Town'; // Cayman Islands
    case GIBRALTAR = 'Gibraltar'; // Gibraltar
    case GITEGA = 'Gitega'; // Burundi
    case GUATEMALA_CITY = 'Guatemala City'; // Guatemala
    case GUSTAVIA = 'Gustavia'; // Saint Barthélemy
    case HAGATNA = 'Hagåtña'; // Guam
    case HAMILTON = 'Hamilton'; // Bermuda
    case HANOI = 'Hanoi'; // Vietnam
    case HARARE = 'Harare'; // Zimbabwe
    case HAVANA = 'Havana'; // Cuba
    case HELSINKI = 'Helsinki'; // Finland
    case HONG_KONG = 'Hong Kong'; // Hong Kong
    case HONIARA = 'Honiara'; // Solomon Islands
    case ISLAMABAD = 'Islamabad'; // Pakistan
    case JAKARTA = 'Jakarta'; // Indonesia
    case JAMESTOWN = 'Jamestown'; // Saint Helena
    case JERUSALEM = 'Jerusalem'; // Israel
    case JUBA = 'Juba'; // South Sudan
    case KABUL = 'Kabul'; // Afghanistan
    case KAMPALA = 'Kampala'; // Uganda
    case KATHMANDU = 'Kathmandu'; // Nepal
    case KHARTOUM = 'Khartoum'; // Sudan
    case KIGALI = 'Kigali'; // Rwanda
    case KINGSTON = 'Kingston'; // Jamaica + Norfolk Island
    case KINGSTOWN = 'Kingstown'; // Saint Vincent and the Grenadines
    case KING_EDWARD_POINT = 'King Edward Point'; // South Georgia and the South Sandwich Islands
    case KINSHASA = 'Kinshasa'; // Democratic Republic of the Congo
    case KRALENDIJK = 'Kralendijk'; // Bonaire
    case KUALA_LUMPUR = 'Kuala Lumpur'; // Malaysia
    case KUWAIT_CITY = 'Kuwait City'; // Kuwait
    case KYIV = 'Kyiv'; // Ukraine
    case LIBREVILLE = 'Libreville'; // Gabon
    case LILONGWE = 'Lilongwe'; // Malawi
    case LIMA = 'Lima'; // Peru
    case LISBON = 'Lisbon'; // Portugal
    case LJUBLJANA = 'Ljubljana'; // Slovenia
    case LOME = 'Lomé'; // Togo
    case LONDON = 'London'; // United Kingdom
    case LONGYEARBYEN = 'Longyearbyen'; // Svalbard
    case LUANDA = 'Luanda'; // Angola
    case LUSAKA = 'Lusaka'; // Zambia
    case LUXEMBOURG = 'Luxembourg'; // Luxembourg
    case MACAO = 'Macao'; // Macao
    case MADRID = 'Madrid'; // Spain
    case MAJURO = 'Majuro'; // Marshall Islands
    case MALABO = 'Malabo'; // Equatorial Guinea
    case MALE = 'Malé'; // Maldives
    case MAMOUDZOU = 'Mamoudzou'; // Mayotte
    case MANAGUA = 'Managua'; // Nicaragua
    case MANAMA = 'Manama'; // Bahrain
    case MANILA = 'Manila'; // Philippines
    case MAPUTO = 'Maputo'; // Mozambique
    case MARIEHAMN = 'Mariehamn'; // Åland Islands
    case MARIGOT = 'Marigot'; // Saint Martin
    case MASERU = 'Maseru'; // Lesotho
    case MATA_UTU = 'Mata-Utu'; // Wallis and Futuna
    case MBABANE = 'Mbabane'; // Eswatini
    case MEXICO_CITY = 'Mexico City'; // Mexico
    case MINSK = 'Minsk'; // Belarus
    case MOGADISHU = 'Mogadishu'; // Somalia
    case MONACO = 'Monaco'; // Monaco
    case MONROVIA = 'Monrovia'; // Liberia
    case MONTEVIDEO = 'Montevideo'; // Uruguay
    case MORONI = 'Moroni'; // Comoros
    case MOSCOW = 'Moscow'; // Russia
    case MUSCAT = 'Muscat'; // Oman
    case NA = 'N/A'; // Not applicable
    case NAIROBI = 'Nairobi'; // Kenya
    case NASSAU = 'Nassau'; // Bahamas
    case NAYPYIDAW = 'Naypyidaw'; // Myanmar
    case NDJAMENA = 'N\'Djamena'; // Chad
    case NEW_DELHI = 'New Delhi'; // India
    case NGERULMUD = 'Ngerulmud'; // Palau
    case NIAMEY = 'Niamey'; // Niger
    case NICOSIA = 'Nicosia'; // Cyprus
    case NONE = 'None'; // Placeholder for no capital
    case NOUAKCHOTT = 'Nouakchott'; // Mauritania
    case NOUMEA = 'Nouméa'; // New Caledonia
    case NUKUALOFA = 'Nuku\'alofa'; // Tonga
    case NUR_SULTAN = 'Nur-Sultan'; // Kazakhstan
    case NUUK = 'Nuuk'; // Greenland
    case ORANJESTAD = 'Oranjestad'; // Aruba
    case OSLO = 'Oslo'; // Norway
    case OTTAWA = 'Ottawa'; // Canada
    case OUAGADOUGOU = 'Ouagadougou'; // Burkina Faso
    case PAGO_PAGO = 'Pago Pago'; // American Samoa
    case PALIKIR = 'Palikir'; // Micronesia
    case PANAMA_CITY = 'Panama City'; // Panama
    case PAPEETE = 'Papeete'; // French Polynesia
    case PARAMARIBO = 'Paramaribo'; // Suriname
    case PARIS = 'Paris'; // France
    case PHILIPSBURG = 'Philipsburg'; // Sint Maarten
    case PHNOM_PENH = 'Phnom Penh'; // Cambodia
    case PLYMOUTH = 'Plymouth'; // Montserrat
    case PODGORICA = 'Podgorica'; // Montenegro
    case PORTO_NOVO = 'Porto-Novo'; // Benin
    case PORT_AUX_FRANCAIS = 'Port-aux-Français'; // Crozet Islands
    case PORT_AU_PRINCE = 'Port-au-Prince'; // Haiti
    case PORT_LOUIS = 'Port Louis'; // Mauritius
    case PORT_MORESBY = 'Port Moresby'; // Papua New Guinea
    case PORT_OF_SPAIN = 'Port of Spain'; // Trinidad and Tobago
    case PORT_VILA = 'Port Vila'; // Vanuatu
    case PRAGUE = 'Prague'; // Czech Republic
    case PRAIA = 'Praia'; // Cape Verde
    case PRETORIA = 'Pretoria'; // South Africa
    case PRISTINA = 'Pristina'; // Kosovo
    case PYONGYANG = 'Pyongyang'; // North Korea
    case QUITO = 'Quito'; // Ecuador
    case RABAT = 'Rabat'; // Morocco
    case REYKJAVIK = 'Reykjavik'; // Iceland
    case RIGA = 'Riga'; // Latvia
    case RIYADH = 'Riyadh'; // Saudi Arabia
    case ROAD_TOWN = 'Road Town'; // British Virgin Islands
    case ROME = 'Rome'; // Italy
    case ROSEAU = 'Roseau'; // Dominica
    case SAINT_DENIS = 'Saint-Denis'; // Réunion
    case SAINT_HELIER = 'Saint Helier'; // Jersey
    case SAINT_JOHNS = 'Saint John\'s'; // Antigua and Barbuda
    case SAINT_PIERRE = 'Saint-Pierre'; // Saint Pierre and Miquelon
    case SAIPAN = 'Saipan'; // Northern Mariana Islands
    case SANA_A = 'Sana\'a'; // Yemen
    case SANTIAGO = 'Santiago'; // Chile
    case SANTO_DOMINGO = 'Santo Domingo'; // Dominican Republic
    case SAN_JOSE = 'San José'; // Costa Rica
    case SAN_JUAN = 'San Juan'; // Puerto Rico
    case SAN_MARINO = 'San Marino'; // San Marino
    case SAN_SALVADOR = 'San Salvador'; // El Salvador
    case SAO_TOME = 'São Tomé'; // São Tomé and Príncipe
    case SARAJEVO = 'Sarajevo'; // Bosnia and Herzegovina
    case SEOUL = 'Seoul'; // South Korea
    case SINGAPORE = 'Singapore'; // Singapore
    case SKOPJE = 'Skopje'; // North Macedonia
    case SOFIA = 'Sofia'; // Bulgaria
    case SOUTH_TARAWA = 'South Tarawa'; // Kiribati
    case STANLEY = 'Stanley'; // Falkland Islands
    case STOCKHOLM = 'Stockholm'; // Sweden
    case ST_GEORGES = 'St. George\'s'; // Grenada
    case ST_PETER_PORT = 'St. Peter Port'; // Guernsey
    case SUCRE = 'Sucre'; // Bolivia
    case SUVA = 'Suva'; // Fiji
    case TAIPEI = 'Taipei'; // Taiwan
    case TALLINN = 'Tallinn'; // Estonia
    case TASHKENT = 'Tashkent'; // Uzbekistan
    case TBILISI = 'Tbilisi'; // Georgia
    case TEGUCIGALPA = 'Tegucigalpa'; // Honduras
    case TEHRAN = 'Tehran'; // Iran
    case THE_VALLEY = 'The Valley'; // Anguilla
    case THIMPHU = 'Thimphu'; // Bhutan
    case TIRANA = 'Tirana'; // Albania
    case TOKYO = 'Tokyo'; // Japan
    case TORSHAVN = 'Tórshavn'; // Faroe Islands
    case TRIPOLI = 'Tripoli'; // Libya
    case TUNIS = 'Tunis'; // Tunisia
    case ULAANBAATAR = 'Ulaanbaatar'; // Mongolia
    case VADUZ = 'Vaduz'; // Liechtenstein
    case VALLETTA = 'Valletta'; // Malta
    case VATICAN_CITY = 'Vatican City'; // Vatican City
    case VICTORIA = 'Victoria'; // Seychelles
    case VIENNA = 'Vienna'; // Austria
    case VIENTIANE = 'Vientiane'; // Laos
    case VILNIUS = 'Vilnius'; // Lithuania
    case WARSAW = 'Warsaw'; // Poland
    case WASHINGTON_DC = 'Washington, D.C.'; // United States
    case WELLINGTON = 'Wellington'; // New Zealand
    case WEST_ISLAND = 'West Island'; // Cocos (Keeling) Islands
    case WILLEMSTAD = 'Willemstad'; // Curaçao
    case WINDHOEK = 'Windhoek'; // Namibia
    case YAMOUSSOUKRO = 'Yamoussoukro'; // Côte d'Ivoire
    case YAOUNDE = 'Yaoundé'; // Cameroon
    case YAREN = 'Yaren'; // Nauru
    case YEREVAN = 'Yerevan'; // Armenia
    case ZAGREB = 'Zagreb'; // Croatia
}
