<?php

namespace Macmotp\Countries\Support;

enum CountryCode: string
{
    case AD = 'AD'; // Andorra
    case AE = 'AE'; // United Arab Emirates
    case AF = 'AF'; // Afghanistan
    case AG = 'AG'; // Antigua and Barbuda
    case AI = 'AI'; // Anguilla
    case AL = 'AL'; // Albania
    case AM = 'AM'; // Armenia
    case AO = 'AO'; // Angola
    case AQ = 'AQ'; // Antarctica
    case AR = 'AR'; // Argentina
    case AS = 'AS'; // American Samoa
    case AT = 'AT'; // Austria
    case AU = 'AU'; // Australia
    case AW = 'AW'; // Aruba
    case AX = 'AX'; // Åland
    case AZ = 'AZ'; // Azerbaijan
    case BA = 'BA'; // Bosnia and Herzegovina
    case BB = 'BB'; // Barbados
    case BD = 'BD'; // Bangladesh
    case BE = 'BE'; // Belgium
    case BF = 'BF'; // Burkina Faso
    case BG = 'BG'; // Bulgaria
    case BH = 'BH'; // Bahrain
    case BI = 'BI'; // Burundi
    case BJ = 'BJ'; // Benin
    case BL = 'BL'; // Saint Barthélemy
    case BM = 'BM'; // Bermuda
    case BN = 'BN'; // Brunei
    case BO = 'BO'; // Bolivia
    case BQ = 'BQ'; // Bonaire
    case BR = 'BR'; // Brazil
    case BS = 'BS'; // Bahamas
    case BT = 'BT'; // Bhutan
    case BV = 'BV'; // Bouvet Island
    case BW = 'BW'; // Botswana
    case BY = 'BY'; // Belarus
    case BZ = 'BZ'; // Belize
    case CA = 'CA'; // Canada
    case CC = 'CC'; // Cocos (Keeling) Islands
    case CD = 'CD'; // Democratic Republic of the Congo
    case CF = 'CF'; // Central African Republic
    case CG = 'CG'; // Republic of the Congo
    case CH = 'CH'; // Switzerland
    case CI = 'CI'; // Ivory Coast
    case CK = 'CK'; // Cook Islands
    case CL = 'CL'; // Chile
    case CM = 'CM'; // Cameroon
    case CN = 'CN'; // China
    case CO = 'CO'; // Colombia
    case CR = 'CR'; // Costa Rica
    case CU = 'CU'; // Cuba
    case CV = 'CV'; // Cape Verde
    case CW = 'CW'; // Curaçao
    case CX = 'CX'; // Christmas Island
    case CY = 'CY'; // Cyprus
    case CZ = 'CZ'; // Czechia
    case DE = 'DE'; // Germany
    case DJ = 'DJ'; // Djibouti
    case DK = 'DK'; // Denmark
    case DM = 'DM'; // Dominica
    case DO = 'DO'; // Dominican Republic
    case DZ = 'DZ'; // Algeria
    case EC = 'EC'; // Ecuador
    case EE = 'EE'; // Estonia
    case EG = 'EG'; // Egypt
    case EH = 'EH'; // Western Sahara
    case ER = 'ER'; // Eritrea
    case ES = 'ES'; // Spain
    case ET = 'ET'; // Ethiopia
    case FI = 'FI'; // Finland
    case FJ = 'FJ'; // Fiji
    case FK = 'FK'; // Falkland Islands
    case FM = 'FM'; // Micronesia
    case FO = 'FO'; // Faroe Islands
    case FR = 'FR'; // France
    case GA = 'GA'; // Gabon
    case GB = 'GB'; // United Kingdom
    case GD = 'GD'; // Grenada
    case GE = 'GE'; // Georgia
    case GF = 'GF'; // French Guiana
    case GG = 'GG'; // Guernsey
    case GH = 'GH'; // Ghana
    case GI = 'GI'; // Gibraltar
    case GL = 'GL'; // Greenland
    case GM = 'GM'; // Gambia
    case GN = 'GN'; // Guinea
    case GP = 'GP'; // Guadeloupe
    case GQ = 'GQ'; // Equatorial Guinea
    case GR = 'GR'; // Greece
    case GS = 'GS'; // South Georgia and the South Sandwich Islands
    case GT = 'GT'; // Guatemala
    case GU = 'GU'; // Guam
    case GW = 'GW'; // Guinea-Bissau
    case GY = 'GY'; // Guyana
    case HK = 'HK'; // Hong Kong
    case HM = 'HM'; // Heard Island and McDonald Islands
    case HN = 'HN'; // Honduras
    case HR = 'HR'; // Croatia
    case HT = 'HT'; // Haiti
    case HU = 'HU'; // Hungary
    case ID = 'ID'; // Indonesia
    case IE = 'IE'; // Ireland
    case IL = 'IL'; // Israel
    case IM = 'IM'; // Isle of Man
    case IN = 'IN'; // India
    case IO = 'IO'; // British Indian Ocean Territory
    case IQ = 'IQ'; // Iraq
    case IR = 'IR'; // Iran
    case IS = 'IS'; // Iceland
    case IT = 'IT'; // Italy
    case JE = 'JE'; // Jersey
    case JM = 'JM'; // Jamaica
    case JO = 'JO'; // Jordan
    case JP = 'JP'; // Japan
    case KE = 'KE'; // Kenya
    case KG = 'KG'; // Kyrgyzstan
    case KH = 'KH'; // Cambodia
    case KI = 'KI'; // Kiribati
    case KM = 'KM'; // Comoros
    case KN = 'KN'; // Saint Kitts and Nevis
    case KP = 'KP'; // North Korea
    case KR = 'KR'; // South Korea
    case KW = 'KW'; // Kuwait
    case KY = 'KY'; // Cayman Islands
    case KZ = 'KZ'; // Kazakhstan
    case LA = 'LA'; // Laos
    case LB = 'LB'; // Lebanon
    case LC = 'LC'; // Saint Lucia
    case LI = 'LI'; // Liechtenstein
    case LK = 'LK'; // Sri Lanka
    case LR = 'LR'; // Liberia
    case LS = 'LS'; // Lesotho
    case LT = 'LT'; // Lithuania
    case LU = 'LU'; // Luxembourg
    case LV = 'LV'; // Latvia
    case LY = 'LY'; // Libya
    case MA = 'MA'; // Morocco
    case MC = 'MC'; // Monaco
    case MD = 'MD'; // Moldova
    case ME = 'ME'; // Montenegro
    case MF = 'MF'; // Saint Martin
    case MG = 'MG'; // Madagascar
    case MH = 'MH'; // Marshall Islands
    case MK = 'MK'; // North Macedonia
    case ML = 'ML'; // Mali
    case MM = 'MM'; // Myanmar
    case MN = 'MN'; // Mongolia
    case MO = 'MO'; // Macao
    case MP = 'MP'; // Northern Mariana Islands
    case MQ = 'MQ'; // Martinique
    case MR = 'MR'; // Mauritania
    case MS = 'MS'; // Montserrat
    case MT = 'MT'; // Malta
    case MU = 'MU'; // Mauritius
    case MV = 'MV'; // Maldives
    case MW = 'MW'; // Malawi
    case MX = 'MX'; // Mexico
    case MY = 'MY'; // Malaysia
    case MZ = 'MZ'; // Mozambique
    case NA = 'NA'; // Namibia
    case NC = 'NC'; // New Caledonia
    case NE = 'NE'; // Niger
    case NF = 'NF'; // Norfolk Island
    case NG = 'NG'; // Nigeria
    case NI = 'NI'; // Nicaragua
    case NL = 'NL'; // Netherlands
    case NO = 'NO'; // Norway
    case NP = 'NP'; // Nepal
    case NR = 'NR'; // Nauru
    case NU = 'NU'; // Niue
    case NZ = 'NZ'; // New Zealand
    case OM = 'OM'; // Oman
    case PA = 'PA'; // Panama
    case PE = 'PE'; // Peru
    case PF = 'PF'; // French Polynesia
    case PG = 'PG'; // Papua New Guinea
    case PH = 'PH'; // Philippines
    case PK = 'PK'; // Pakistan
    case PL = 'PL'; // Poland
    case PM = 'PM'; // Saint Pierre and Miquelon
    case PN = 'PN'; // Pitcairn Islands
    case PR = 'PR'; // Puerto Rico
    case PS = 'PS'; // Palestine
    case PT = 'PT'; // Portugal
    case PW = 'PW'; // Palau
    case PY = 'PY'; // Paraguay
    case QA = 'QA'; // Qatar
    case RE = 'RE'; // Réunion
    case RO = 'RO'; // Romania
    case RS = 'RS'; // Serbia
    case RU = 'RU'; // Russia
    case RW = 'RW'; // Rwanda
    case SA = 'SA'; // Saudi Arabia
    case SB = 'SB'; // Solomon Islands
    case SC = 'SC'; // Seychelles
    case SD = 'SD'; // Sudan
    case SE = 'SE'; // Sweden
    case SG = 'SG'; // Singapore
    case SH = 'SH'; // Saint Helena
    case SI = 'SI'; // Slovenia
    case SJ = 'SJ'; // Svalbard and Jan Mayen
    case SK = 'SK'; // Slovakia
    case SL = 'SL'; // Sierra Leone
    case SM = 'SM'; // San Marino
    case SN = 'SN'; // Senegal
    case SO = 'SO'; // Somalia
    case SR = 'SR'; // Suriname
    case SS = 'SS'; // South Sudan
    case ST = 'ST'; // São Tomé and Príncipe
    case SV = 'SV'; // El Salvador
    case SX = 'SX'; // Sint Maarten
    case SY = 'SY'; // Syria
    case SZ = 'SZ'; // Eswatini
    case TC = 'TC'; // Turks and Caicos Islands
    case TD = 'TD'; // Chad
    case TF = 'TF'; // French Southern Territories
    case TG = 'TG'; // Togo
    case TH = 'TH'; // Thailand
    case TJ = 'TJ'; // Tajikistan
    case TK = 'TK'; // Tokelau
    case TL = 'TL'; // Timor-Leste
    case TM = 'TM'; // Turkmenistan
    case TN = 'TN'; // Tunisia
    case TO = 'TO'; // Tonga
    case TR = 'TR'; // Turkey
    case TT = 'TT'; // Trinidad and Tobago
    case TV = 'TV'; // Tuvalu
    case TW = 'TW'; // Taiwan
    case TZ = 'TZ'; // Tanzania
    case UA = 'UA'; // Ukraine
    case UG = 'UG'; // Uganda
    case UM = 'UM'; // U.S. Minor Outlying Islands
    case US = 'US'; // United States of America
    case UY = 'UY'; // Uruguay
    case UZ = 'UZ'; // Uzbekistan
    case VA = 'VA'; // Vatican City
    case VC = 'VC'; // Saint Vincent and the Grenadines
    case VE = 'VE'; // Venezuela
    case VG = 'VG'; // Virgin Islands (British)
    case VI = 'VI'; // Virgin Islands (U.S.)
    case VN = 'VN'; // Viet Nam
    case VU = 'VU'; // Vanuatu
    case WF = 'WF'; // Wallis and Futuna
    case WS = 'WS'; // Samoa
    case XK = 'XK'; // Kosovo
    case YE = 'YE'; // Yemen
    case YT = 'YT'; // Mayotte
    case ZA = 'ZA'; // South Africa
    case ZM = 'ZM'; // Zambia
    case ZW = 'ZW'; // Zimbabwe
}
