<?php

namespace Macmotp\Locale\Tests\Unit;

use Macmotp\Timezone;
use Macmotp\Timezones\Exceptions\InvalidTimezoneCodeException;
use Macmotp\Timezones\Support\TimezoneCode;
use PHPUnit\Framework\TestCase;

/**
 * Class TimezoneTest
 *
 * @package Macmotp\Locale\Tests\Unit
 * @group Locale
 */
class TimezoneTest extends TestCase
{
    /**
     * @dataProvider listConstructors
     *
     * @param TimezoneCode $timezoneCode
     * @param string $outputCode
     * @param string $outputName
     * @return void
     * @throws InvalidTimezoneCodeException
     */
    public function testTimezoneConstructor(
        TimezoneCode $timezoneCode,
        string $outputCode,
        string $outputName
    ): void {
        $timezone = new Timezone($timezoneCode);

        $this->assertEquals($outputCode, $timezone->getCode());
        $this->assertEquals($outputName, $timezone->getName());
    }

    /**
     * @return void
     * @throws InvalidTimezoneCodeException
     */
    public function testMakeFunction(): void
    {
        $timezone = Timezone::make(TimezoneCode::EUROPE_LONDON);

        $this->assertEquals('Europe/London', $timezone->getCode());
        $this->assertEquals('Europe/London', $timezone->getName());
    }

    /**
     * @return void
     */
    public function testStringConstructor(): void
    {
        $timezone = new Timezone('Europe/London');

        $this->assertEquals('Europe/London', $timezone->getCode());
    }

    /**
     * @return void
     * @throws InvalidTimezoneCodeException
     */
    public function testToArrayFunction(): void
    {
        $timezone = Timezone::make(TimezoneCode::EUROPE_LONDON);

        $this->assertEquals([
            'code' => 'Europe/London',
            'name' => 'Europe/London',
        ], $timezone->toArray());
    }

    /**
     * @return void
     * @throws InvalidTimezoneCodeException
     */
    public function testGetAllTimezonesFunction(): void
    {
        $this->assertCount(419, Timezone::all());
    }

    /**
     * List of different constructors
     *
     * @return array[]
     */
    public static function listConstructors(): array
    {
        return [
            [TimezoneCode::AFRICA_ABIDJAN, TimezoneCode::AFRICA_ABIDJAN->value, TimezoneCode::AFRICA_ABIDJAN->value],
            [TimezoneCode::AFRICA_ACCRA, TimezoneCode::AFRICA_ACCRA->value, TimezoneCode::AFRICA_ACCRA->value],
            [TimezoneCode::AFRICA_ADDIS_ABABA, TimezoneCode::AFRICA_ADDIS_ABABA->value, TimezoneCode::AFRICA_ADDIS_ABABA->value],
            [TimezoneCode::AFRICA_ALGIERS, TimezoneCode::AFRICA_ALGIERS->value, TimezoneCode::AFRICA_ALGIERS->value],
            [TimezoneCode::AFRICA_ASMARA, TimezoneCode::AFRICA_ASMARA->value, TimezoneCode::AFRICA_ASMARA->value],
            [TimezoneCode::AFRICA_BAMAKO, TimezoneCode::AFRICA_BAMAKO->value, TimezoneCode::AFRICA_BAMAKO->value],
            [TimezoneCode::AFRICA_BANGUI, TimezoneCode::AFRICA_BANGUI->value, TimezoneCode::AFRICA_BANGUI->value],
            [TimezoneCode::AFRICA_BANJUL, TimezoneCode::AFRICA_BANJUL->value, TimezoneCode::AFRICA_BANJUL->value],
            [TimezoneCode::AFRICA_BISSAU, TimezoneCode::AFRICA_BISSAU->value, TimezoneCode::AFRICA_BISSAU->value],
            [TimezoneCode::AFRICA_BLANTYRE, TimezoneCode::AFRICA_BLANTYRE->value, TimezoneCode::AFRICA_BLANTYRE->value],
            [TimezoneCode::AFRICA_BRAZZAVILLE, TimezoneCode::AFRICA_BRAZZAVILLE->value, TimezoneCode::AFRICA_BRAZZAVILLE->value],
            [TimezoneCode::AFRICA_BUJUMBURA, TimezoneCode::AFRICA_BUJUMBURA->value, TimezoneCode::AFRICA_BUJUMBURA->value],
            [TimezoneCode::AFRICA_CAIRO, TimezoneCode::AFRICA_CAIRO->value, TimezoneCode::AFRICA_CAIRO->value],
            [TimezoneCode::AFRICA_CASABLANCA, TimezoneCode::AFRICA_CASABLANCA->value, TimezoneCode::AFRICA_CASABLANCA->value],
            [TimezoneCode::AFRICA_CEUTA, TimezoneCode::AFRICA_CEUTA->value, TimezoneCode::AFRICA_CEUTA->value],
            [TimezoneCode::AFRICA_CONAKRY, TimezoneCode::AFRICA_CONAKRY->value, TimezoneCode::AFRICA_CONAKRY->value],
            [TimezoneCode::AFRICA_DAKAR, TimezoneCode::AFRICA_DAKAR->value, TimezoneCode::AFRICA_DAKAR->value],
            [TimezoneCode::AFRICA_DAR_ES_SALAAM, TimezoneCode::AFRICA_DAR_ES_SALAAM->value, TimezoneCode::AFRICA_DAR_ES_SALAAM->value],
            [TimezoneCode::AFRICA_DJIBOUTI, TimezoneCode::AFRICA_DJIBOUTI->value, TimezoneCode::AFRICA_DJIBOUTI->value],
            [TimezoneCode::AFRICA_DOUALA, TimezoneCode::AFRICA_DOUALA->value, TimezoneCode::AFRICA_DOUALA->value],
            [TimezoneCode::AFRICA_EL_AAIUN, TimezoneCode::AFRICA_EL_AAIUN->value, TimezoneCode::AFRICA_EL_AAIUN->value],
            [TimezoneCode::AFRICA_FREETOWN, TimezoneCode::AFRICA_FREETOWN->value, TimezoneCode::AFRICA_FREETOWN->value],
            [TimezoneCode::AFRICA_GABORONE, TimezoneCode::AFRICA_GABORONE->value, TimezoneCode::AFRICA_GABORONE->value],
            [TimezoneCode::AFRICA_HARARE, TimezoneCode::AFRICA_HARARE->value, TimezoneCode::AFRICA_HARARE->value],
            [TimezoneCode::AFRICA_JOHANNESBURG, TimezoneCode::AFRICA_JOHANNESBURG->value, TimezoneCode::AFRICA_JOHANNESBURG->value],
            [TimezoneCode::AFRICA_JUBA, TimezoneCode::AFRICA_JUBA->value, TimezoneCode::AFRICA_JUBA->value],
            [TimezoneCode::AFRICA_KAMPALA, TimezoneCode::AFRICA_KAMPALA->value, TimezoneCode::AFRICA_KAMPALA->value],
            [TimezoneCode::AFRICA_KHARTOUM, TimezoneCode::AFRICA_KHARTOUM->value, TimezoneCode::AFRICA_KHARTOUM->value],
            [TimezoneCode::AFRICA_KIGALI, TimezoneCode::AFRICA_KIGALI->value, TimezoneCode::AFRICA_KIGALI->value],
            [TimezoneCode::AFRICA_KINSHASA, TimezoneCode::AFRICA_KINSHASA->value, TimezoneCode::AFRICA_KINSHASA->value],
            [TimezoneCode::AFRICA_LAGOS, TimezoneCode::AFRICA_LAGOS->value, TimezoneCode::AFRICA_LAGOS->value],
            [TimezoneCode::AFRICA_LIBREVILLE, TimezoneCode::AFRICA_LIBREVILLE->value, TimezoneCode::AFRICA_LIBREVILLE->value],
            [TimezoneCode::AFRICA_LOME, TimezoneCode::AFRICA_LOME->value, TimezoneCode::AFRICA_LOME->value],
            [TimezoneCode::AFRICA_LUANDA, TimezoneCode::AFRICA_LUANDA->value, TimezoneCode::AFRICA_LUANDA->value],
            [TimezoneCode::AFRICA_LUBUMBASHI, TimezoneCode::AFRICA_LUBUMBASHI->value, TimezoneCode::AFRICA_LUBUMBASHI->value],
            [TimezoneCode::AFRICA_LUSAKA, TimezoneCode::AFRICA_LUSAKA->value, TimezoneCode::AFRICA_LUSAKA->value],
            [TimezoneCode::AFRICA_MALABO, TimezoneCode::AFRICA_MALABO->value, TimezoneCode::AFRICA_MALABO->value],
            [TimezoneCode::AFRICA_MAPUTO, TimezoneCode::AFRICA_MAPUTO->value, TimezoneCode::AFRICA_MAPUTO->value],
            [TimezoneCode::AFRICA_MASERU, TimezoneCode::AFRICA_MASERU->value, TimezoneCode::AFRICA_MASERU->value],
            [TimezoneCode::AFRICA_MBABANE, TimezoneCode::AFRICA_MBABANE->value, TimezoneCode::AFRICA_MBABANE->value],
            [TimezoneCode::AFRICA_MOGADISHU, TimezoneCode::AFRICA_MOGADISHU->value, TimezoneCode::AFRICA_MOGADISHU->value],
            [TimezoneCode::AFRICA_MONROVIA, TimezoneCode::AFRICA_MONROVIA->value, TimezoneCode::AFRICA_MONROVIA->value],
            [TimezoneCode::AFRICA_NAIROBI, TimezoneCode::AFRICA_NAIROBI->value, TimezoneCode::AFRICA_NAIROBI->value],
            [TimezoneCode::AFRICA_NDJAMENA, TimezoneCode::AFRICA_NDJAMENA->value, TimezoneCode::AFRICA_NDJAMENA->value],
            [TimezoneCode::AFRICA_NIAMEY, TimezoneCode::AFRICA_NIAMEY->value, TimezoneCode::AFRICA_NIAMEY->value],
            [TimezoneCode::AFRICA_NOUAKCHOTT, TimezoneCode::AFRICA_NOUAKCHOTT->value, TimezoneCode::AFRICA_NOUAKCHOTT->value],
            [TimezoneCode::AFRICA_OUAGADOUGOU, TimezoneCode::AFRICA_OUAGADOUGOU->value, TimezoneCode::AFRICA_OUAGADOUGOU->value],
            [TimezoneCode::AFRICA_PORTO_NOVO, TimezoneCode::AFRICA_PORTO_NOVO->value, TimezoneCode::AFRICA_PORTO_NOVO->value],
            [TimezoneCode::AFRICA_SAO_TOME, TimezoneCode::AFRICA_SAO_TOME->value, TimezoneCode::AFRICA_SAO_TOME->value],
            [TimezoneCode::AFRICA_TRIPOLI, TimezoneCode::AFRICA_TRIPOLI->value, TimezoneCode::AFRICA_TRIPOLI->value],
            [TimezoneCode::AFRICA_TUNIS, TimezoneCode::AFRICA_TUNIS->value, TimezoneCode::AFRICA_TUNIS->value],
            [TimezoneCode::AFRICA_WINDHOEK, TimezoneCode::AFRICA_WINDHOEK->value, TimezoneCode::AFRICA_WINDHOEK->value],
            [TimezoneCode::AMERICA_ADAK, TimezoneCode::AMERICA_ADAK->value, TimezoneCode::AMERICA_ADAK->value],
            [TimezoneCode::AMERICA_ANCHORAGE, TimezoneCode::AMERICA_ANCHORAGE->value, TimezoneCode::AMERICA_ANCHORAGE->value],
            [TimezoneCode::AMERICA_ANGUILLA, TimezoneCode::AMERICA_ANGUILLA->value, TimezoneCode::AMERICA_ANGUILLA->value],
            [TimezoneCode::AMERICA_ANTIGUA, TimezoneCode::AMERICA_ANTIGUA->value, TimezoneCode::AMERICA_ANTIGUA->value],
            [TimezoneCode::AMERICA_ARAGUAINA, TimezoneCode::AMERICA_ARAGUAINA->value, TimezoneCode::AMERICA_ARAGUAINA->value],
            [TimezoneCode::AMERICA_ARGENTINA_BUENOS_AIRES, TimezoneCode::AMERICA_ARGENTINA_BUENOS_AIRES->value, TimezoneCode::AMERICA_ARGENTINA_BUENOS_AIRES->value],
            [TimezoneCode::AMERICA_ARGENTINA_CATAMARCA, TimezoneCode::AMERICA_ARGENTINA_CATAMARCA->value, TimezoneCode::AMERICA_ARGENTINA_CATAMARCA->value],
            [TimezoneCode::AMERICA_ARGENTINA_CORDOBA, TimezoneCode::AMERICA_ARGENTINA_CORDOBA->value, TimezoneCode::AMERICA_ARGENTINA_CORDOBA->value],
            [TimezoneCode::AMERICA_ARGENTINA_JUJUY, TimezoneCode::AMERICA_ARGENTINA_JUJUY->value, TimezoneCode::AMERICA_ARGENTINA_JUJUY->value],
            [TimezoneCode::AMERICA_ARGENTINA_LA_RIOJA, TimezoneCode::AMERICA_ARGENTINA_LA_RIOJA->value, TimezoneCode::AMERICA_ARGENTINA_LA_RIOJA->value],
            [TimezoneCode::AMERICA_ARGENTINA_MENDOZA, TimezoneCode::AMERICA_ARGENTINA_MENDOZA->value, TimezoneCode::AMERICA_ARGENTINA_MENDOZA->value],
            [TimezoneCode::AMERICA_ARGENTINA_RIO_GALLEGOS, TimezoneCode::AMERICA_ARGENTINA_RIO_GALLEGOS->value, TimezoneCode::AMERICA_ARGENTINA_RIO_GALLEGOS->value],
            [TimezoneCode::AMERICA_ARGENTINA_SALTA, TimezoneCode::AMERICA_ARGENTINA_SALTA->value, TimezoneCode::AMERICA_ARGENTINA_SALTA->value],
            [TimezoneCode::AMERICA_ARGENTINA_SAN_JUAN, TimezoneCode::AMERICA_ARGENTINA_SAN_JUAN->value, TimezoneCode::AMERICA_ARGENTINA_SAN_JUAN->value],
            [TimezoneCode::AMERICA_ARGENTINA_SAN_LUIS, TimezoneCode::AMERICA_ARGENTINA_SAN_LUIS->value, TimezoneCode::AMERICA_ARGENTINA_SAN_LUIS->value],
            [TimezoneCode::AMERICA_ARGENTINA_TUCUMAN, TimezoneCode::AMERICA_ARGENTINA_TUCUMAN->value, TimezoneCode::AMERICA_ARGENTINA_TUCUMAN->value],
            [TimezoneCode::AMERICA_ARGENTINA_USHUAIA, TimezoneCode::AMERICA_ARGENTINA_USHUAIA->value, TimezoneCode::AMERICA_ARGENTINA_USHUAIA->value],
            [TimezoneCode::AMERICA_ARUBA, TimezoneCode::AMERICA_ARUBA->value, TimezoneCode::AMERICA_ARUBA->value],
            [TimezoneCode::AMERICA_ASUNCION, TimezoneCode::AMERICA_ASUNCION->value, TimezoneCode::AMERICA_ASUNCION->value],
            [TimezoneCode::AMERICA_ATIKOKAN, TimezoneCode::AMERICA_ATIKOKAN->value, TimezoneCode::AMERICA_ATIKOKAN->value],
            [TimezoneCode::AMERICA_BAHIA, TimezoneCode::AMERICA_BAHIA->value, TimezoneCode::AMERICA_BAHIA->value],
            [TimezoneCode::AMERICA_BAHIA_BANDERAS, TimezoneCode::AMERICA_BAHIA_BANDERAS->value, TimezoneCode::AMERICA_BAHIA_BANDERAS->value],
            [TimezoneCode::AMERICA_BARBADOS, TimezoneCode::AMERICA_BARBADOS->value, TimezoneCode::AMERICA_BARBADOS->value],
            [TimezoneCode::AMERICA_BELEM, TimezoneCode::AMERICA_BELEM->value, TimezoneCode::AMERICA_BELEM->value],
            [TimezoneCode::AMERICA_BELIZE, TimezoneCode::AMERICA_BELIZE->value, TimezoneCode::AMERICA_BELIZE->value],
            [TimezoneCode::AMERICA_BLANC_SABLON, TimezoneCode::AMERICA_BLANC_SABLON->value, TimezoneCode::AMERICA_BLANC_SABLON->value],
            [TimezoneCode::AMERICA_BOA_VISTA, TimezoneCode::AMERICA_BOA_VISTA->value, TimezoneCode::AMERICA_BOA_VISTA->value],
            [TimezoneCode::AMERICA_BOGOTA, TimezoneCode::AMERICA_BOGOTA->value, TimezoneCode::AMERICA_BOGOTA->value],
            [TimezoneCode::AMERICA_BOISE, TimezoneCode::AMERICA_BOISE->value, TimezoneCode::AMERICA_BOISE->value],
            [TimezoneCode::AMERICA_CAMBRIDGE_BAY, TimezoneCode::AMERICA_CAMBRIDGE_BAY->value, TimezoneCode::AMERICA_CAMBRIDGE_BAY->value],
            [TimezoneCode::AMERICA_CAMPO_GRANDE, TimezoneCode::AMERICA_CAMPO_GRANDE->value, TimezoneCode::AMERICA_CAMPO_GRANDE->value],
            [TimezoneCode::AMERICA_CANCUN, TimezoneCode::AMERICA_CANCUN->value, TimezoneCode::AMERICA_CANCUN->value],
            [TimezoneCode::AMERICA_CARACAS, TimezoneCode::AMERICA_CARACAS->value, TimezoneCode::AMERICA_CARACAS->value],
            [TimezoneCode::AMERICA_CAYENNE, TimezoneCode::AMERICA_CAYENNE->value, TimezoneCode::AMERICA_CAYENNE->value],
            [TimezoneCode::AMERICA_CAYMAN, TimezoneCode::AMERICA_CAYMAN->value, TimezoneCode::AMERICA_CAYMAN->value],
            [TimezoneCode::AMERICA_CHICAGO, TimezoneCode::AMERICA_CHICAGO->value, TimezoneCode::AMERICA_CHICAGO->value],
            [TimezoneCode::AMERICA_CHIHUAHUA, TimezoneCode::AMERICA_CHIHUAHUA->value, TimezoneCode::AMERICA_CHIHUAHUA->value],
            [TimezoneCode::AMERICA_CIUDAD_JUAREZ, TimezoneCode::AMERICA_CIUDAD_JUAREZ->value, TimezoneCode::AMERICA_CIUDAD_JUAREZ->value],
            [TimezoneCode::AMERICA_COSTA_RICA, TimezoneCode::AMERICA_COSTA_RICA->value, TimezoneCode::AMERICA_COSTA_RICA->value],
            [TimezoneCode::AMERICA_CRESTON, TimezoneCode::AMERICA_CRESTON->value, TimezoneCode::AMERICA_CRESTON->value],
            [TimezoneCode::AMERICA_CUIABA, TimezoneCode::AMERICA_CUIABA->value, TimezoneCode::AMERICA_CUIABA->value],
            [TimezoneCode::AMERICA_CURACAO, TimezoneCode::AMERICA_CURACAO->value, TimezoneCode::AMERICA_CURACAO->value],
            [TimezoneCode::AMERICA_DANMARKSHAVN, TimezoneCode::AMERICA_DANMARKSHAVN->value, TimezoneCode::AMERICA_DANMARKSHAVN->value],
            [TimezoneCode::AMERICA_DAWSON, TimezoneCode::AMERICA_DAWSON->value, TimezoneCode::AMERICA_DAWSON->value],
            [TimezoneCode::AMERICA_DAWSON_CREEK, TimezoneCode::AMERICA_DAWSON_CREEK->value, TimezoneCode::AMERICA_DAWSON_CREEK->value],
            [TimezoneCode::AMERICA_DENVER, TimezoneCode::AMERICA_DENVER->value, TimezoneCode::AMERICA_DENVER->value],
            [TimezoneCode::AMERICA_DETROIT, TimezoneCode::AMERICA_DETROIT->value, TimezoneCode::AMERICA_DETROIT->value],
            [TimezoneCode::AMERICA_DOMINICA, TimezoneCode::AMERICA_DOMINICA->value, TimezoneCode::AMERICA_DOMINICA->value],
            [TimezoneCode::AMERICA_EDMONTON, TimezoneCode::AMERICA_EDMONTON->value, TimezoneCode::AMERICA_EDMONTON->value],
            [TimezoneCode::AMERICA_EIRUNEPE, TimezoneCode::AMERICA_EIRUNEPE->value, TimezoneCode::AMERICA_EIRUNEPE->value],
            [TimezoneCode::AMERICA_EL_SALVADOR, TimezoneCode::AMERICA_EL_SALVADOR->value, TimezoneCode::AMERICA_EL_SALVADOR->value],
            [TimezoneCode::AMERICA_FORT_NELSON, TimezoneCode::AMERICA_FORT_NELSON->value, TimezoneCode::AMERICA_FORT_NELSON->value],
            [TimezoneCode::AMERICA_FORTALEZA, TimezoneCode::AMERICA_FORTALEZA->value, TimezoneCode::AMERICA_FORTALEZA->value],
            [TimezoneCode::AMERICA_GLACE_BAY, TimezoneCode::AMERICA_GLACE_BAY->value, TimezoneCode::AMERICA_GLACE_BAY->value],
            [TimezoneCode::AMERICA_GOOSE_BAY, TimezoneCode::AMERICA_GOOSE_BAY->value, TimezoneCode::AMERICA_GOOSE_BAY->value],
            [TimezoneCode::AMERICA_GRAND_TURK, TimezoneCode::AMERICA_GRAND_TURK->value, TimezoneCode::AMERICA_GRAND_TURK->value],
            [TimezoneCode::AMERICA_GRENADA, TimezoneCode::AMERICA_GRENADA->value, TimezoneCode::AMERICA_GRENADA->value],
            [TimezoneCode::AMERICA_GUADELOUPE, TimezoneCode::AMERICA_GUADELOUPE->value, TimezoneCode::AMERICA_GUADELOUPE->value],
            [TimezoneCode::AMERICA_GUATEMALA, TimezoneCode::AMERICA_GUATEMALA->value, TimezoneCode::AMERICA_GUATEMALA->value],
            [TimezoneCode::AMERICA_GUAYAQUIL, TimezoneCode::AMERICA_GUAYAQUIL->value, TimezoneCode::AMERICA_GUAYAQUIL->value],
            [TimezoneCode::AMERICA_GUYANA, TimezoneCode::AMERICA_GUYANA->value, TimezoneCode::AMERICA_GUYANA->value],
            [TimezoneCode::AMERICA_HALIFAX, TimezoneCode::AMERICA_HALIFAX->value, TimezoneCode::AMERICA_HALIFAX->value],
            [TimezoneCode::AMERICA_HAVANA, TimezoneCode::AMERICA_HAVANA->value, TimezoneCode::AMERICA_HAVANA->value],
            [TimezoneCode::AMERICA_HERMOSILLO, TimezoneCode::AMERICA_HERMOSILLO->value, TimezoneCode::AMERICA_HERMOSILLO->value],
            [TimezoneCode::AMERICA_INDIANA_INDIANAPOLIS, TimezoneCode::AMERICA_INDIANA_INDIANAPOLIS->value, TimezoneCode::AMERICA_INDIANA_INDIANAPOLIS->value],
            [TimezoneCode::AMERICA_INDIANA_KNOX, TimezoneCode::AMERICA_INDIANA_KNOX->value, TimezoneCode::AMERICA_INDIANA_KNOX->value],
            [TimezoneCode::AMERICA_INDIANA_MARENGO, TimezoneCode::AMERICA_INDIANA_MARENGO->value, TimezoneCode::AMERICA_INDIANA_MARENGO->value],
            [TimezoneCode::AMERICA_INDIANA_PETERSBURG, TimezoneCode::AMERICA_INDIANA_PETERSBURG->value, TimezoneCode::AMERICA_INDIANA_PETERSBURG->value],
            [TimezoneCode::AMERICA_INDIANA_TELL_CITY, TimezoneCode::AMERICA_INDIANA_TELL_CITY->value, TimezoneCode::AMERICA_INDIANA_TELL_CITY->value],
            [TimezoneCode::AMERICA_INDIANA_VEVAY, TimezoneCode::AMERICA_INDIANA_VEVAY->value, TimezoneCode::AMERICA_INDIANA_VEVAY->value],
            [TimezoneCode::AMERICA_INDIANA_VINCENNES, TimezoneCode::AMERICA_INDIANA_VINCENNES->value, TimezoneCode::AMERICA_INDIANA_VINCENNES->value],
            [TimezoneCode::AMERICA_INDIANA_WINAMAC, TimezoneCode::AMERICA_INDIANA_WINAMAC->value, TimezoneCode::AMERICA_INDIANA_WINAMAC->value],
            [TimezoneCode::AMERICA_INUVIK, TimezoneCode::AMERICA_INUVIK->value, TimezoneCode::AMERICA_INUVIK->value],
            [TimezoneCode::AMERICA_IQALUIT, TimezoneCode::AMERICA_IQALUIT->value, TimezoneCode::AMERICA_IQALUIT->value],
            [TimezoneCode::AMERICA_JAMAICA, TimezoneCode::AMERICA_JAMAICA->value, TimezoneCode::AMERICA_JAMAICA->value],
            [TimezoneCode::AMERICA_JUNEAU, TimezoneCode::AMERICA_JUNEAU->value, TimezoneCode::AMERICA_JUNEAU->value],
            [TimezoneCode::AMERICA_KENTUCKY_LOUISVILLE, TimezoneCode::AMERICA_KENTUCKY_LOUISVILLE->value, TimezoneCode::AMERICA_KENTUCKY_LOUISVILLE->value],
            [TimezoneCode::AMERICA_KENTUCKY_MONTICELLO, TimezoneCode::AMERICA_KENTUCKY_MONTICELLO->value, TimezoneCode::AMERICA_KENTUCKY_MONTICELLO->value],
            [TimezoneCode::AMERICA_KRALENDIJK, TimezoneCode::AMERICA_KRALENDIJK->value, TimezoneCode::AMERICA_KRALENDIJK->value],
            [TimezoneCode::AMERICA_LA_PAZ, TimezoneCode::AMERICA_LA_PAZ->value, TimezoneCode::AMERICA_LA_PAZ->value],
            [TimezoneCode::AMERICA_LIMA, TimezoneCode::AMERICA_LIMA->value, TimezoneCode::AMERICA_LIMA->value],
            [TimezoneCode::AMERICA_LOS_ANGELES, TimezoneCode::AMERICA_LOS_ANGELES->value, TimezoneCode::AMERICA_LOS_ANGELES->value],
            [TimezoneCode::AMERICA_LOWER_PRINCES, TimezoneCode::AMERICA_LOWER_PRINCES->value, TimezoneCode::AMERICA_LOWER_PRINCES->value],
            [TimezoneCode::AMERICA_MACEIO, TimezoneCode::AMERICA_MACEIO->value, TimezoneCode::AMERICA_MACEIO->value],
            [TimezoneCode::AMERICA_MANAGUA, TimezoneCode::AMERICA_MANAGUA->value, TimezoneCode::AMERICA_MANAGUA->value],
            [TimezoneCode::AMERICA_MANAUS, TimezoneCode::AMERICA_MANAUS->value, TimezoneCode::AMERICA_MANAUS->value],
            [TimezoneCode::AMERICA_MARIGOT, TimezoneCode::AMERICA_MARIGOT->value, TimezoneCode::AMERICA_MARIGOT->value],
            [TimezoneCode::AMERICA_MARTINIQUE, TimezoneCode::AMERICA_MARTINIQUE->value, TimezoneCode::AMERICA_MARTINIQUE->value],
            [TimezoneCode::AMERICA_MATAMOROS, TimezoneCode::AMERICA_MATAMOROS->value, TimezoneCode::AMERICA_MATAMOROS->value],
            [TimezoneCode::AMERICA_MAZATLAN, TimezoneCode::AMERICA_MAZATLAN->value, TimezoneCode::AMERICA_MAZATLAN->value],
            [TimezoneCode::AMERICA_MENOMINEE, TimezoneCode::AMERICA_MENOMINEE->value, TimezoneCode::AMERICA_MENOMINEE->value],
            [TimezoneCode::AMERICA_MERIDA, TimezoneCode::AMERICA_MERIDA->value, TimezoneCode::AMERICA_MERIDA->value],
            [TimezoneCode::AMERICA_METLAKATLA, TimezoneCode::AMERICA_METLAKATLA->value, TimezoneCode::AMERICA_METLAKATLA->value],
            [TimezoneCode::AMERICA_MEXICO_CITY, TimezoneCode::AMERICA_MEXICO_CITY->value, TimezoneCode::AMERICA_MEXICO_CITY->value],
            [TimezoneCode::AMERICA_MIQUELON, TimezoneCode::AMERICA_MIQUELON->value, TimezoneCode::AMERICA_MIQUELON->value],
            [TimezoneCode::AMERICA_MONCTON, TimezoneCode::AMERICA_MONCTON->value, TimezoneCode::AMERICA_MONCTON->value],
            [TimezoneCode::AMERICA_MONTERREY, TimezoneCode::AMERICA_MONTERREY->value, TimezoneCode::AMERICA_MONTERREY->value],
            [TimezoneCode::AMERICA_MONTEVIDEO, TimezoneCode::AMERICA_MONTEVIDEO->value, TimezoneCode::AMERICA_MONTEVIDEO->value],
            [TimezoneCode::AMERICA_MONTSERRAT, TimezoneCode::AMERICA_MONTSERRAT->value, TimezoneCode::AMERICA_MONTSERRAT->value],
            [TimezoneCode::AMERICA_NASSAU, TimezoneCode::AMERICA_NASSAU->value, TimezoneCode::AMERICA_NASSAU->value],
            [TimezoneCode::AMERICA_NEW_YORK, TimezoneCode::AMERICA_NEW_YORK->value, TimezoneCode::AMERICA_NEW_YORK->value],
            [TimezoneCode::AMERICA_NOME, TimezoneCode::AMERICA_NOME->value, TimezoneCode::AMERICA_NOME->value],
            [TimezoneCode::AMERICA_NORONHA, TimezoneCode::AMERICA_NORONHA->value, TimezoneCode::AMERICA_NORONHA->value],
            [TimezoneCode::AMERICA_NORTH_DAKOTA_BEULAH, TimezoneCode::AMERICA_NORTH_DAKOTA_BEULAH->value, TimezoneCode::AMERICA_NORTH_DAKOTA_BEULAH->value],
            [TimezoneCode::AMERICA_NORTH_DAKOTA_CENTER, TimezoneCode::AMERICA_NORTH_DAKOTA_CENTER->value, TimezoneCode::AMERICA_NORTH_DAKOTA_CENTER->value],
            [TimezoneCode::AMERICA_NORTH_DAKOTA_NEW_SALEM, TimezoneCode::AMERICA_NORTH_DAKOTA_NEW_SALEM->value, TimezoneCode::AMERICA_NORTH_DAKOTA_NEW_SALEM->value],
            [TimezoneCode::AMERICA_NUUK, TimezoneCode::AMERICA_NUUK->value, TimezoneCode::AMERICA_NUUK->value],
            [TimezoneCode::AMERICA_OJINAGA, TimezoneCode::AMERICA_OJINAGA->value, TimezoneCode::AMERICA_OJINAGA->value],
            [TimezoneCode::AMERICA_PANAMA, TimezoneCode::AMERICA_PANAMA->value, TimezoneCode::AMERICA_PANAMA->value],
            [TimezoneCode::AMERICA_PARAMARIBO, TimezoneCode::AMERICA_PARAMARIBO->value, TimezoneCode::AMERICA_PARAMARIBO->value],
            [TimezoneCode::AMERICA_PHOENIX, TimezoneCode::AMERICA_PHOENIX->value, TimezoneCode::AMERICA_PHOENIX->value],
            [TimezoneCode::AMERICA_PORT_AU_PRINCE, TimezoneCode::AMERICA_PORT_AU_PRINCE->value, TimezoneCode::AMERICA_PORT_AU_PRINCE->value],
            [TimezoneCode::AMERICA_PORT_OF_SPAIN, TimezoneCode::AMERICA_PORT_OF_SPAIN->value, TimezoneCode::AMERICA_PORT_OF_SPAIN->value],
            [TimezoneCode::AMERICA_PORTO_VELHO, TimezoneCode::AMERICA_PORTO_VELHO->value, TimezoneCode::AMERICA_PORTO_VELHO->value],
            [TimezoneCode::AMERICA_PUERTO_RICO, TimezoneCode::AMERICA_PUERTO_RICO->value, TimezoneCode::AMERICA_PUERTO_RICO->value],
            [TimezoneCode::AMERICA_PUNTA_ARENAS, TimezoneCode::AMERICA_PUNTA_ARENAS->value, TimezoneCode::AMERICA_PUNTA_ARENAS->value],
            [TimezoneCode::AMERICA_RANKIN_INLET, TimezoneCode::AMERICA_RANKIN_INLET->value, TimezoneCode::AMERICA_RANKIN_INLET->value],
            [TimezoneCode::AMERICA_RECIFE, TimezoneCode::AMERICA_RECIFE->value, TimezoneCode::AMERICA_RECIFE->value],
            [TimezoneCode::AMERICA_REGINA, TimezoneCode::AMERICA_REGINA->value, TimezoneCode::AMERICA_REGINA->value],
            [TimezoneCode::AMERICA_RESOLUTE, TimezoneCode::AMERICA_RESOLUTE->value, TimezoneCode::AMERICA_RESOLUTE->value],
            [TimezoneCode::AMERICA_RIO_BRANCO, TimezoneCode::AMERICA_RIO_BRANCO->value, TimezoneCode::AMERICA_RIO_BRANCO->value],
            [TimezoneCode::AMERICA_SANTAREM, TimezoneCode::AMERICA_SANTAREM->value, TimezoneCode::AMERICA_SANTAREM->value],
            [TimezoneCode::AMERICA_SANTIAGO, TimezoneCode::AMERICA_SANTIAGO->value, TimezoneCode::AMERICA_SANTIAGO->value],
            [TimezoneCode::AMERICA_SANTO_DOMINGO, TimezoneCode::AMERICA_SANTO_DOMINGO->value, TimezoneCode::AMERICA_SANTO_DOMINGO->value],
            [TimezoneCode::AMERICA_SAO_PAULO, TimezoneCode::AMERICA_SAO_PAULO->value, TimezoneCode::AMERICA_SAO_PAULO->value],
            [TimezoneCode::AMERICA_SCORESBYSUND, TimezoneCode::AMERICA_SCORESBYSUND->value, TimezoneCode::AMERICA_SCORESBYSUND->value],
            [TimezoneCode::AMERICA_SITKA, TimezoneCode::AMERICA_SITKA->value, TimezoneCode::AMERICA_SITKA->value],
            [TimezoneCode::AMERICA_ST_BARTHELEMY, TimezoneCode::AMERICA_ST_BARTHELEMY->value, TimezoneCode::AMERICA_ST_BARTHELEMY->value],
            [TimezoneCode::AMERICA_ST_JOHNS, TimezoneCode::AMERICA_ST_JOHNS->value, TimezoneCode::AMERICA_ST_JOHNS->value],
            [TimezoneCode::AMERICA_ST_KITTS, TimezoneCode::AMERICA_ST_KITTS->value, TimezoneCode::AMERICA_ST_KITTS->value],
            [TimezoneCode::AMERICA_ST_LUCIA, TimezoneCode::AMERICA_ST_LUCIA->value, TimezoneCode::AMERICA_ST_LUCIA->value],
            [TimezoneCode::AMERICA_ST_THOMAS, TimezoneCode::AMERICA_ST_THOMAS->value, TimezoneCode::AMERICA_ST_THOMAS->value],
            [TimezoneCode::AMERICA_ST_VINCENT, TimezoneCode::AMERICA_ST_VINCENT->value, TimezoneCode::AMERICA_ST_VINCENT->value],
            [TimezoneCode::AMERICA_SWIFT_CURRENT, TimezoneCode::AMERICA_SWIFT_CURRENT->value, TimezoneCode::AMERICA_SWIFT_CURRENT->value],
            [TimezoneCode::AMERICA_TEGUCIGALPA, TimezoneCode::AMERICA_TEGUCIGALPA->value, TimezoneCode::AMERICA_TEGUCIGALPA->value],
            [TimezoneCode::AMERICA_THULE, TimezoneCode::AMERICA_THULE->value, TimezoneCode::AMERICA_THULE->value],
            [TimezoneCode::AMERICA_TIJUANA, TimezoneCode::AMERICA_TIJUANA->value, TimezoneCode::AMERICA_TIJUANA->value],
            [TimezoneCode::AMERICA_TORONTO, TimezoneCode::AMERICA_TORONTO->value, TimezoneCode::AMERICA_TORONTO->value],
            [TimezoneCode::AMERICA_TORTOLA, TimezoneCode::AMERICA_TORTOLA->value, TimezoneCode::AMERICA_TORTOLA->value],
            [TimezoneCode::AMERICA_VANCOUVER, TimezoneCode::AMERICA_VANCOUVER->value, TimezoneCode::AMERICA_VANCOUVER->value],
            [TimezoneCode::AMERICA_WHITEHORSE, TimezoneCode::AMERICA_WHITEHORSE->value, TimezoneCode::AMERICA_WHITEHORSE->value],
            [TimezoneCode::AMERICA_WINNIPEG, TimezoneCode::AMERICA_WINNIPEG->value, TimezoneCode::AMERICA_WINNIPEG->value],
            [TimezoneCode::AMERICA_YAKUTAT, TimezoneCode::AMERICA_YAKUTAT->value, TimezoneCode::AMERICA_YAKUTAT->value],
            [TimezoneCode::ANTARCTICA_CASEY, TimezoneCode::ANTARCTICA_CASEY->value, TimezoneCode::ANTARCTICA_CASEY->value],
            [TimezoneCode::ANTARCTICA_DAVIS, TimezoneCode::ANTARCTICA_DAVIS->value, TimezoneCode::ANTARCTICA_DAVIS->value],
            [TimezoneCode::ANTARCTICA_DUMONT_D_URVILLE, TimezoneCode::ANTARCTICA_DUMONT_D_URVILLE->value, TimezoneCode::ANTARCTICA_DUMONT_D_URVILLE->value],
            [TimezoneCode::ANTARCTICA_MACQUARIE, TimezoneCode::ANTARCTICA_MACQUARIE->value, TimezoneCode::ANTARCTICA_MACQUARIE->value],
            [TimezoneCode::ANTARCTICA_MAWSON, TimezoneCode::ANTARCTICA_MAWSON->value, TimezoneCode::ANTARCTICA_MAWSON->value],
            [TimezoneCode::ANTARCTICA_MC_MURDO, TimezoneCode::ANTARCTICA_MC_MURDO->value, TimezoneCode::ANTARCTICA_MC_MURDO->value],
            [TimezoneCode::ANTARCTICA_PALMER, TimezoneCode::ANTARCTICA_PALMER->value, TimezoneCode::ANTARCTICA_PALMER->value],
            [TimezoneCode::ANTARCTICA_ROTHERA, TimezoneCode::ANTARCTICA_ROTHERA->value, TimezoneCode::ANTARCTICA_ROTHERA->value],
            [TimezoneCode::ANTARCTICA_SYOWA, TimezoneCode::ANTARCTICA_SYOWA->value, TimezoneCode::ANTARCTICA_SYOWA->value],
            [TimezoneCode::ANTARCTICA_TROLL, TimezoneCode::ANTARCTICA_TROLL->value, TimezoneCode::ANTARCTICA_TROLL->value],
            [TimezoneCode::ANTARCTICA_VOSTOK, TimezoneCode::ANTARCTICA_VOSTOK->value, TimezoneCode::ANTARCTICA_VOSTOK->value],
            [TimezoneCode::ARCTIC_LONGYEARBYEN, TimezoneCode::ARCTIC_LONGYEARBYEN->value, TimezoneCode::ARCTIC_LONGYEARBYEN->value],
            [TimezoneCode::ASIA_ADEN, TimezoneCode::ASIA_ADEN->value, TimezoneCode::ASIA_ADEN->value],
            [TimezoneCode::ASIA_ALMATY, TimezoneCode::ASIA_ALMATY->value, TimezoneCode::ASIA_ALMATY->value],
            [TimezoneCode::ASIA_AMMAN, TimezoneCode::ASIA_AMMAN->value, TimezoneCode::ASIA_AMMAN->value],
            [TimezoneCode::ASIA_ANADYR, TimezoneCode::ASIA_ANADYR->value, TimezoneCode::ASIA_ANADYR->value],
            [TimezoneCode::ASIA_AQTAU, TimezoneCode::ASIA_AQTAU->value, TimezoneCode::ASIA_AQTAU->value],
            [TimezoneCode::ASIA_AQTOBE, TimezoneCode::ASIA_AQTOBE->value, TimezoneCode::ASIA_AQTOBE->value],
            [TimezoneCode::ASIA_ASHGABAT, TimezoneCode::ASIA_ASHGABAT->value, TimezoneCode::ASIA_ASHGABAT->value],
            [TimezoneCode::ASIA_ATYRAU, TimezoneCode::ASIA_ATYRAU->value, TimezoneCode::ASIA_ATYRAU->value],
            [TimezoneCode::ASIA_BAGHDAD, TimezoneCode::ASIA_BAGHDAD->value, TimezoneCode::ASIA_BAGHDAD->value],
            [TimezoneCode::ASIA_BAHRAIN, TimezoneCode::ASIA_BAHRAIN->value, TimezoneCode::ASIA_BAHRAIN->value],
            [TimezoneCode::ASIA_BAKU, TimezoneCode::ASIA_BAKU->value, TimezoneCode::ASIA_BAKU->value],
            [TimezoneCode::ASIA_BANGKOK, TimezoneCode::ASIA_BANGKOK->value, TimezoneCode::ASIA_BANGKOK->value],
            [TimezoneCode::ASIA_BARNAUL, TimezoneCode::ASIA_BARNAUL->value, TimezoneCode::ASIA_BARNAUL->value],
            [TimezoneCode::ASIA_BEIRUT, TimezoneCode::ASIA_BEIRUT->value, TimezoneCode::ASIA_BEIRUT->value],
            [TimezoneCode::ASIA_BISHKEK, TimezoneCode::ASIA_BISHKEK->value, TimezoneCode::ASIA_BISHKEK->value],
            [TimezoneCode::ASIA_BRUNEI, TimezoneCode::ASIA_BRUNEI->value, TimezoneCode::ASIA_BRUNEI->value],
            [TimezoneCode::ASIA_CHITA, TimezoneCode::ASIA_CHITA->value, TimezoneCode::ASIA_CHITA->value],
            [TimezoneCode::ASIA_CHOIBALSAN, TimezoneCode::ASIA_CHOIBALSAN->value, TimezoneCode::ASIA_CHOIBALSAN->value],
            [TimezoneCode::ASIA_COLOMBO, TimezoneCode::ASIA_COLOMBO->value, TimezoneCode::ASIA_COLOMBO->value],
            [TimezoneCode::ASIA_DAMASCUS, TimezoneCode::ASIA_DAMASCUS->value, TimezoneCode::ASIA_DAMASCUS->value],
            [TimezoneCode::ASIA_DHAKA, TimezoneCode::ASIA_DHAKA->value, TimezoneCode::ASIA_DHAKA->value],
            [TimezoneCode::ASIA_DILI, TimezoneCode::ASIA_DILI->value, TimezoneCode::ASIA_DILI->value],
            [TimezoneCode::ASIA_DUBAI, TimezoneCode::ASIA_DUBAI->value, TimezoneCode::ASIA_DUBAI->value],
            [TimezoneCode::ASIA_DUSHANBE, TimezoneCode::ASIA_DUSHANBE->value, TimezoneCode::ASIA_DUSHANBE->value],
            [TimezoneCode::ASIA_FAMAGUSTA, TimezoneCode::ASIA_FAMAGUSTA->value, TimezoneCode::ASIA_FAMAGUSTA->value],
            [TimezoneCode::ASIA_GAZA, TimezoneCode::ASIA_GAZA->value, TimezoneCode::ASIA_GAZA->value],
            [TimezoneCode::ASIA_HEBRON, TimezoneCode::ASIA_HEBRON->value, TimezoneCode::ASIA_HEBRON->value],
            [TimezoneCode::ASIA_HO_CHI_MINH, TimezoneCode::ASIA_HO_CHI_MINH->value, TimezoneCode::ASIA_HO_CHI_MINH->value],
            [TimezoneCode::ASIA_HONG_KONG, TimezoneCode::ASIA_HONG_KONG->value, TimezoneCode::ASIA_HONG_KONG->value],
            [TimezoneCode::ASIA_HOVD, TimezoneCode::ASIA_HOVD->value, TimezoneCode::ASIA_HOVD->value],
            [TimezoneCode::ASIA_IRKUTSK, TimezoneCode::ASIA_IRKUTSK->value, TimezoneCode::ASIA_IRKUTSK->value],
            [TimezoneCode::ASIA_JAKARTA, TimezoneCode::ASIA_JAKARTA->value, TimezoneCode::ASIA_JAKARTA->value],
            [TimezoneCode::ASIA_JAYAPURA, TimezoneCode::ASIA_JAYAPURA->value, TimezoneCode::ASIA_JAYAPURA->value],
            [TimezoneCode::ASIA_JERUSALEM, TimezoneCode::ASIA_JERUSALEM->value, TimezoneCode::ASIA_JERUSALEM->value],
            [TimezoneCode::ASIA_KABUL, TimezoneCode::ASIA_KABUL->value, TimezoneCode::ASIA_KABUL->value],
            [TimezoneCode::ASIA_KAMCHATKA, TimezoneCode::ASIA_KAMCHATKA->value, TimezoneCode::ASIA_KAMCHATKA->value],
            [TimezoneCode::ASIA_KARACHI, TimezoneCode::ASIA_KARACHI->value, TimezoneCode::ASIA_KARACHI->value],
            [TimezoneCode::ASIA_KATHMANDU, TimezoneCode::ASIA_KATHMANDU->value, TimezoneCode::ASIA_KATHMANDU->value],
            [TimezoneCode::ASIA_KHANDYGA, TimezoneCode::ASIA_KHANDYGA->value, TimezoneCode::ASIA_KHANDYGA->value],
            [TimezoneCode::ASIA_KOLKATA, TimezoneCode::ASIA_KOLKATA->value, TimezoneCode::ASIA_KOLKATA->value],
            [TimezoneCode::ASIA_KRASNOYARSK, TimezoneCode::ASIA_KRASNOYARSK->value, TimezoneCode::ASIA_KRASNOYARSK->value],
            [TimezoneCode::ASIA_KUALA_LUMPUR, TimezoneCode::ASIA_KUALA_LUMPUR->value, TimezoneCode::ASIA_KUALA_LUMPUR->value],
            [TimezoneCode::ASIA_KUCHING, TimezoneCode::ASIA_KUCHING->value, TimezoneCode::ASIA_KUCHING->value],
            [TimezoneCode::ASIA_KUWAIT, TimezoneCode::ASIA_KUWAIT->value, TimezoneCode::ASIA_KUWAIT->value],
            [TimezoneCode::ASIA_MACAU, TimezoneCode::ASIA_MACAU->value, TimezoneCode::ASIA_MACAU->value],
            [TimezoneCode::ASIA_MAGADAN, TimezoneCode::ASIA_MAGADAN->value, TimezoneCode::ASIA_MAGADAN->value],
            [TimezoneCode::ASIA_MAKASSAR, TimezoneCode::ASIA_MAKASSAR->value, TimezoneCode::ASIA_MAKASSAR->value],
            [TimezoneCode::ASIA_MANILA, TimezoneCode::ASIA_MANILA->value, TimezoneCode::ASIA_MANILA->value],
            [TimezoneCode::ASIA_MUSCAT, TimezoneCode::ASIA_MUSCAT->value, TimezoneCode::ASIA_MUSCAT->value],
            [TimezoneCode::ASIA_NICOSIA, TimezoneCode::ASIA_NICOSIA->value, TimezoneCode::ASIA_NICOSIA->value],
            [TimezoneCode::ASIA_NOVOKUZNETSK, TimezoneCode::ASIA_NOVOKUZNETSK->value, TimezoneCode::ASIA_NOVOKUZNETSK->value],
            [TimezoneCode::ASIA_NOVOSIBIRSK, TimezoneCode::ASIA_NOVOSIBIRSK->value, TimezoneCode::ASIA_NOVOSIBIRSK->value],
            [TimezoneCode::ASIA_OMSK, TimezoneCode::ASIA_OMSK->value, TimezoneCode::ASIA_OMSK->value],
            [TimezoneCode::ASIA_ORAL, TimezoneCode::ASIA_ORAL->value, TimezoneCode::ASIA_ORAL->value],
            [TimezoneCode::ASIA_PHNOM_PENH, TimezoneCode::ASIA_PHNOM_PENH->value, TimezoneCode::ASIA_PHNOM_PENH->value],
            [TimezoneCode::ASIA_PONTIANAK, TimezoneCode::ASIA_PONTIANAK->value, TimezoneCode::ASIA_PONTIANAK->value],
            [TimezoneCode::ASIA_PYONGYANG, TimezoneCode::ASIA_PYONGYANG->value, TimezoneCode::ASIA_PYONGYANG->value],
            [TimezoneCode::ASIA_QATAR, TimezoneCode::ASIA_QATAR->value, TimezoneCode::ASIA_QATAR->value],
            [TimezoneCode::ASIA_QOSTANAY, TimezoneCode::ASIA_QOSTANAY->value, TimezoneCode::ASIA_QOSTANAY->value],
            [TimezoneCode::ASIA_QYZYLORDA, TimezoneCode::ASIA_QYZYLORDA->value, TimezoneCode::ASIA_QYZYLORDA->value],
            [TimezoneCode::ASIA_RIYADH, TimezoneCode::ASIA_RIYADH->value, TimezoneCode::ASIA_RIYADH->value],
            [TimezoneCode::ASIA_SAKHALIN, TimezoneCode::ASIA_SAKHALIN->value, TimezoneCode::ASIA_SAKHALIN->value],
            [TimezoneCode::ASIA_SAMARKAND, TimezoneCode::ASIA_SAMARKAND->value, TimezoneCode::ASIA_SAMARKAND->value],
            [TimezoneCode::ASIA_SEOUL, TimezoneCode::ASIA_SEOUL->value, TimezoneCode::ASIA_SEOUL->value],
            [TimezoneCode::ASIA_SHANGHAI, TimezoneCode::ASIA_SHANGHAI->value, TimezoneCode::ASIA_SHANGHAI->value],
            [TimezoneCode::ASIA_SINGAPORE, TimezoneCode::ASIA_SINGAPORE->value, TimezoneCode::ASIA_SINGAPORE->value],
            [TimezoneCode::ASIA_SREDNEKOLYMSK, TimezoneCode::ASIA_SREDNEKOLYMSK->value, TimezoneCode::ASIA_SREDNEKOLYMSK->value],
            [TimezoneCode::ASIA_TAIPEI, TimezoneCode::ASIA_TAIPEI->value, TimezoneCode::ASIA_TAIPEI->value],
            [TimezoneCode::ASIA_TASHKENT, TimezoneCode::ASIA_TASHKENT->value, TimezoneCode::ASIA_TASHKENT->value],
            [TimezoneCode::ASIA_TBILISI, TimezoneCode::ASIA_TBILISI->value, TimezoneCode::ASIA_TBILISI->value],
            [TimezoneCode::ASIA_TEHRAN, TimezoneCode::ASIA_TEHRAN->value, TimezoneCode::ASIA_TEHRAN->value],
            [TimezoneCode::ASIA_THIMPHU, TimezoneCode::ASIA_THIMPHU->value, TimezoneCode::ASIA_THIMPHU->value],
            [TimezoneCode::ASIA_TOKYO, TimezoneCode::ASIA_TOKYO->value, TimezoneCode::ASIA_TOKYO->value],
            [TimezoneCode::ASIA_TOMSK, TimezoneCode::ASIA_TOMSK->value, TimezoneCode::ASIA_TOMSK->value],
            [TimezoneCode::ASIA_ULAANBAATAR, TimezoneCode::ASIA_ULAANBAATAR->value, TimezoneCode::ASIA_ULAANBAATAR->value],
            [TimezoneCode::ASIA_URUMQI, TimezoneCode::ASIA_URUMQI->value, TimezoneCode::ASIA_URUMQI->value],
            [TimezoneCode::ASIA_UST_NERA, TimezoneCode::ASIA_UST_NERA->value, TimezoneCode::ASIA_UST_NERA->value],
            [TimezoneCode::ASIA_VIENTIANE, TimezoneCode::ASIA_VIENTIANE->value, TimezoneCode::ASIA_VIENTIANE->value],
            [TimezoneCode::ASIA_VLADIVOSTOK, TimezoneCode::ASIA_VLADIVOSTOK->value, TimezoneCode::ASIA_VLADIVOSTOK->value],
            [TimezoneCode::ASIA_YAKUTSK, TimezoneCode::ASIA_YAKUTSK->value, TimezoneCode::ASIA_YAKUTSK->value],
            [TimezoneCode::ASIA_YANGON, TimezoneCode::ASIA_YANGON->value, TimezoneCode::ASIA_YANGON->value],
            [TimezoneCode::ASIA_YEKATERINBURG, TimezoneCode::ASIA_YEKATERINBURG->value, TimezoneCode::ASIA_YEKATERINBURG->value],
            [TimezoneCode::ASIA_YEREVAN, TimezoneCode::ASIA_YEREVAN->value, TimezoneCode::ASIA_YEREVAN->value],
            [TimezoneCode::ATLANTIC_AZORES, TimezoneCode::ATLANTIC_AZORES->value, TimezoneCode::ATLANTIC_AZORES->value],
            [TimezoneCode::ATLANTIC_BERMUDA, TimezoneCode::ATLANTIC_BERMUDA->value, TimezoneCode::ATLANTIC_BERMUDA->value],
            [TimezoneCode::ATLANTIC_CANARY, TimezoneCode::ATLANTIC_CANARY->value, TimezoneCode::ATLANTIC_CANARY->value],
            [TimezoneCode::ATLANTIC_CAPE_VERDE, TimezoneCode::ATLANTIC_CAPE_VERDE->value, TimezoneCode::ATLANTIC_CAPE_VERDE->value],
            [TimezoneCode::ATLANTIC_FAROE, TimezoneCode::ATLANTIC_FAROE->value, TimezoneCode::ATLANTIC_FAROE->value],
            [TimezoneCode::ATLANTIC_MADEIRA, TimezoneCode::ATLANTIC_MADEIRA->value, TimezoneCode::ATLANTIC_MADEIRA->value],
            [TimezoneCode::ATLANTIC_REYKJAVIK, TimezoneCode::ATLANTIC_REYKJAVIK->value, TimezoneCode::ATLANTIC_REYKJAVIK->value],
            [TimezoneCode::ATLANTIC_SOUTH_GEORGIA, TimezoneCode::ATLANTIC_SOUTH_GEORGIA->value, TimezoneCode::ATLANTIC_SOUTH_GEORGIA->value],
            [TimezoneCode::ATLANTIC_ST_HELENA, TimezoneCode::ATLANTIC_ST_HELENA->value, TimezoneCode::ATLANTIC_ST_HELENA->value],
            [TimezoneCode::ATLANTIC_STANLEY, TimezoneCode::ATLANTIC_STANLEY->value, TimezoneCode::ATLANTIC_STANLEY->value],
            [TimezoneCode::AUSTRALIA_ADELAIDE, TimezoneCode::AUSTRALIA_ADELAIDE->value, TimezoneCode::AUSTRALIA_ADELAIDE->value],
            [TimezoneCode::AUSTRALIA_BRISBANE, TimezoneCode::AUSTRALIA_BRISBANE->value, TimezoneCode::AUSTRALIA_BRISBANE->value],
            [TimezoneCode::AUSTRALIA_BROKEN_HILL, TimezoneCode::AUSTRALIA_BROKEN_HILL->value, TimezoneCode::AUSTRALIA_BROKEN_HILL->value],
            [TimezoneCode::AUSTRALIA_DARWIN, TimezoneCode::AUSTRALIA_DARWIN->value, TimezoneCode::AUSTRALIA_DARWIN->value],
            [TimezoneCode::AUSTRALIA_EUCLA, TimezoneCode::AUSTRALIA_EUCLA->value, TimezoneCode::AUSTRALIA_EUCLA->value],
            [TimezoneCode::AUSTRALIA_HOBART, TimezoneCode::AUSTRALIA_HOBART->value, TimezoneCode::AUSTRALIA_HOBART->value],
            [TimezoneCode::AUSTRALIA_LINDEMAN, TimezoneCode::AUSTRALIA_LINDEMAN->value, TimezoneCode::AUSTRALIA_LINDEMAN->value],
            [TimezoneCode::AUSTRALIA_LORD_HOWE, TimezoneCode::AUSTRALIA_LORD_HOWE->value, TimezoneCode::AUSTRALIA_LORD_HOWE->value],
            [TimezoneCode::AUSTRALIA_MELBOURNE, TimezoneCode::AUSTRALIA_MELBOURNE->value, TimezoneCode::AUSTRALIA_MELBOURNE->value],
            [TimezoneCode::AUSTRALIA_PERTH, TimezoneCode::AUSTRALIA_PERTH->value, TimezoneCode::AUSTRALIA_PERTH->value],
            [TimezoneCode::AUSTRALIA_SYDNEY, TimezoneCode::AUSTRALIA_SYDNEY->value, TimezoneCode::AUSTRALIA_SYDNEY->value],
            [TimezoneCode::EUROPE_AMSTERDAM, TimezoneCode::EUROPE_AMSTERDAM->value, TimezoneCode::EUROPE_AMSTERDAM->value],
            [TimezoneCode::EUROPE_ANDORRA, TimezoneCode::EUROPE_ANDORRA->value, TimezoneCode::EUROPE_ANDORRA->value],
            [TimezoneCode::EUROPE_ASTRAKHAN, TimezoneCode::EUROPE_ASTRAKHAN->value, TimezoneCode::EUROPE_ASTRAKHAN->value],
            [TimezoneCode::EUROPE_ATHENS, TimezoneCode::EUROPE_ATHENS->value, TimezoneCode::EUROPE_ATHENS->value],
            [TimezoneCode::EUROPE_BELGRADE, TimezoneCode::EUROPE_BELGRADE->value, TimezoneCode::EUROPE_BELGRADE->value],
            [TimezoneCode::EUROPE_BERLIN, TimezoneCode::EUROPE_BERLIN->value, TimezoneCode::EUROPE_BERLIN->value],
            [TimezoneCode::EUROPE_BRATISLAVA, TimezoneCode::EUROPE_BRATISLAVA->value, TimezoneCode::EUROPE_BRATISLAVA->value],
            [TimezoneCode::EUROPE_BRUSSELS, TimezoneCode::EUROPE_BRUSSELS->value, TimezoneCode::EUROPE_BRUSSELS->value],
            [TimezoneCode::EUROPE_BUCHAREST, TimezoneCode::EUROPE_BUCHAREST->value, TimezoneCode::EUROPE_BUCHAREST->value],
            [TimezoneCode::EUROPE_BUDAPEST, TimezoneCode::EUROPE_BUDAPEST->value, TimezoneCode::EUROPE_BUDAPEST->value],
            [TimezoneCode::EUROPE_BUSINGEN, TimezoneCode::EUROPE_BUSINGEN->value, TimezoneCode::EUROPE_BUSINGEN->value],
            [TimezoneCode::EUROPE_CHISINAU, TimezoneCode::EUROPE_CHISINAU->value, TimezoneCode::EUROPE_CHISINAU->value],
            [TimezoneCode::EUROPE_COPENHAGEN, TimezoneCode::EUROPE_COPENHAGEN->value, TimezoneCode::EUROPE_COPENHAGEN->value],
            [TimezoneCode::EUROPE_DUBLIN, TimezoneCode::EUROPE_DUBLIN->value, TimezoneCode::EUROPE_DUBLIN->value],
            [TimezoneCode::EUROPE_GIBRALTAR, TimezoneCode::EUROPE_GIBRALTAR->value, TimezoneCode::EUROPE_GIBRALTAR->value],
            [TimezoneCode::EUROPE_GUERNSEY, TimezoneCode::EUROPE_GUERNSEY->value, TimezoneCode::EUROPE_GUERNSEY->value],
            [TimezoneCode::EUROPE_HELSINKI, TimezoneCode::EUROPE_HELSINKI->value, TimezoneCode::EUROPE_HELSINKI->value],
            [TimezoneCode::EUROPE_ISLE_OF_MAN, TimezoneCode::EUROPE_ISLE_OF_MAN->value, TimezoneCode::EUROPE_ISLE_OF_MAN->value],
            [TimezoneCode::EUROPE_ISTANBUL, TimezoneCode::EUROPE_ISTANBUL->value, TimezoneCode::EUROPE_ISTANBUL->value],
            [TimezoneCode::EUROPE_JERSEY, TimezoneCode::EUROPE_JERSEY->value, TimezoneCode::EUROPE_JERSEY->value],
            [TimezoneCode::EUROPE_KALININGRAD, TimezoneCode::EUROPE_KALININGRAD->value, TimezoneCode::EUROPE_KALININGRAD->value],
            [TimezoneCode::EUROPE_KIROV, TimezoneCode::EUROPE_KIROV->value, TimezoneCode::EUROPE_KIROV->value],
            [TimezoneCode::EUROPE_KYIV, TimezoneCode::EUROPE_KYIV->value, TimezoneCode::EUROPE_KYIV->value],
            [TimezoneCode::EUROPE_LISBON, TimezoneCode::EUROPE_LISBON->value, TimezoneCode::EUROPE_LISBON->value],
            [TimezoneCode::EUROPE_LJUBLJANA, TimezoneCode::EUROPE_LJUBLJANA->value, TimezoneCode::EUROPE_LJUBLJANA->value],
            [TimezoneCode::EUROPE_LONDON, TimezoneCode::EUROPE_LONDON->value, TimezoneCode::EUROPE_LONDON->value],
            [TimezoneCode::EUROPE_LUXEMBOURG, TimezoneCode::EUROPE_LUXEMBOURG->value, TimezoneCode::EUROPE_LUXEMBOURG->value],
            [TimezoneCode::EUROPE_MADRID, TimezoneCode::EUROPE_MADRID->value, TimezoneCode::EUROPE_MADRID->value],
            [TimezoneCode::EUROPE_MALTA, TimezoneCode::EUROPE_MALTA->value, TimezoneCode::EUROPE_MALTA->value],
            [TimezoneCode::EUROPE_MARIEHAMN, TimezoneCode::EUROPE_MARIEHAMN->value, TimezoneCode::EUROPE_MARIEHAMN->value],
            [TimezoneCode::EUROPE_MINSK, TimezoneCode::EUROPE_MINSK->value, TimezoneCode::EUROPE_MINSK->value],
            [TimezoneCode::EUROPE_MONACO, TimezoneCode::EUROPE_MONACO->value, TimezoneCode::EUROPE_MONACO->value],
            [TimezoneCode::EUROPE_MOSCOW, TimezoneCode::EUROPE_MOSCOW->value, TimezoneCode::EUROPE_MOSCOW->value],
            [TimezoneCode::EUROPE_OSLO, TimezoneCode::EUROPE_OSLO->value, TimezoneCode::EUROPE_OSLO->value],
            [TimezoneCode::EUROPE_PARIS, TimezoneCode::EUROPE_PARIS->value, TimezoneCode::EUROPE_PARIS->value],
            [TimezoneCode::EUROPE_PODGORICA, TimezoneCode::EUROPE_PODGORICA->value, TimezoneCode::EUROPE_PODGORICA->value],
            [TimezoneCode::EUROPE_PRAGUE, TimezoneCode::EUROPE_PRAGUE->value, TimezoneCode::EUROPE_PRAGUE->value],
            [TimezoneCode::EUROPE_RIGA, TimezoneCode::EUROPE_RIGA->value, TimezoneCode::EUROPE_RIGA->value],
            [TimezoneCode::EUROPE_ROME, TimezoneCode::EUROPE_ROME->value, TimezoneCode::EUROPE_ROME->value],
            [TimezoneCode::EUROPE_SAMARA, TimezoneCode::EUROPE_SAMARA->value, TimezoneCode::EUROPE_SAMARA->value],
            [TimezoneCode::EUROPE_SAN_MARINO, TimezoneCode::EUROPE_SAN_MARINO->value, TimezoneCode::EUROPE_SAN_MARINO->value],
            [TimezoneCode::EUROPE_SARAJEVO, TimezoneCode::EUROPE_SARAJEVO->value, TimezoneCode::EUROPE_SARAJEVO->value],
            [TimezoneCode::EUROPE_SARATOV, TimezoneCode::EUROPE_SARATOV->value, TimezoneCode::EUROPE_SARATOV->value],
            [TimezoneCode::EUROPE_SIMFEROPOL, TimezoneCode::EUROPE_SIMFEROPOL->value, TimezoneCode::EUROPE_SIMFEROPOL->value],
            [TimezoneCode::EUROPE_SKOPJE, TimezoneCode::EUROPE_SKOPJE->value, TimezoneCode::EUROPE_SKOPJE->value],
            [TimezoneCode::EUROPE_SOFIA, TimezoneCode::EUROPE_SOFIA->value, TimezoneCode::EUROPE_SOFIA->value],
            [TimezoneCode::EUROPE_STOCKHOLM, TimezoneCode::EUROPE_STOCKHOLM->value, TimezoneCode::EUROPE_STOCKHOLM->value],
            [TimezoneCode::EUROPE_TALLINN, TimezoneCode::EUROPE_TALLINN->value, TimezoneCode::EUROPE_TALLINN->value],
            [TimezoneCode::EUROPE_TIRANE, TimezoneCode::EUROPE_TIRANE->value, TimezoneCode::EUROPE_TIRANE->value],
            [TimezoneCode::EUROPE_ULYANOVSK, TimezoneCode::EUROPE_ULYANOVSK->value, TimezoneCode::EUROPE_ULYANOVSK->value],
            [TimezoneCode::EUROPE_VADUZ, TimezoneCode::EUROPE_VADUZ->value, TimezoneCode::EUROPE_VADUZ->value],
            [TimezoneCode::EUROPE_VATICAN, TimezoneCode::EUROPE_VATICAN->value, TimezoneCode::EUROPE_VATICAN->value],
            [TimezoneCode::EUROPE_VIENNA, TimezoneCode::EUROPE_VIENNA->value, TimezoneCode::EUROPE_VIENNA->value],
            [TimezoneCode::EUROPE_VILNIUS, TimezoneCode::EUROPE_VILNIUS->value, TimezoneCode::EUROPE_VILNIUS->value],
            [TimezoneCode::EUROPE_VOLGOGRAD, TimezoneCode::EUROPE_VOLGOGRAD->value, TimezoneCode::EUROPE_VOLGOGRAD->value],
            [TimezoneCode::EUROPE_WARSAW, TimezoneCode::EUROPE_WARSAW->value, TimezoneCode::EUROPE_WARSAW->value],
            [TimezoneCode::EUROPE_ZAGREB, TimezoneCode::EUROPE_ZAGREB->value, TimezoneCode::EUROPE_ZAGREB->value],
            [TimezoneCode::EUROPE_ZURICH, TimezoneCode::EUROPE_ZURICH->value, TimezoneCode::EUROPE_ZURICH->value],
            [TimezoneCode::INDIAN_ANTANANARIVO, TimezoneCode::INDIAN_ANTANANARIVO->value, TimezoneCode::INDIAN_ANTANANARIVO->value],
            [TimezoneCode::INDIAN_CHAGOS, TimezoneCode::INDIAN_CHAGOS->value, TimezoneCode::INDIAN_CHAGOS->value],
            [TimezoneCode::INDIAN_CHRISTMAS, TimezoneCode::INDIAN_CHRISTMAS->value, TimezoneCode::INDIAN_CHRISTMAS->value],
            [TimezoneCode::INDIAN_COCOS, TimezoneCode::INDIAN_COCOS->value, TimezoneCode::INDIAN_COCOS->value],
            [TimezoneCode::INDIAN_COMORO, TimezoneCode::INDIAN_COMORO->value, TimezoneCode::INDIAN_COMORO->value],
            [TimezoneCode::INDIAN_KERGUELEN, TimezoneCode::INDIAN_KERGUELEN->value, TimezoneCode::INDIAN_KERGUELEN->value],
            [TimezoneCode::INDIAN_MAHE, TimezoneCode::INDIAN_MAHE->value, TimezoneCode::INDIAN_MAHE->value],
            [TimezoneCode::INDIAN_MALDIVES, TimezoneCode::INDIAN_MALDIVES->value, TimezoneCode::INDIAN_MALDIVES->value],
            [TimezoneCode::INDIAN_MAURITIUS, TimezoneCode::INDIAN_MAURITIUS->value, TimezoneCode::INDIAN_MAURITIUS->value],
            [TimezoneCode::INDIAN_MAYOTTE, TimezoneCode::INDIAN_MAYOTTE->value, TimezoneCode::INDIAN_MAYOTTE->value],
            [TimezoneCode::INDIAN_REUNION, TimezoneCode::INDIAN_REUNION->value, TimezoneCode::INDIAN_REUNION->value],
            [TimezoneCode::PACIFIC_APIA, TimezoneCode::PACIFIC_APIA->value, TimezoneCode::PACIFIC_APIA->value],
            [TimezoneCode::PACIFIC_AUCKLAND, TimezoneCode::PACIFIC_AUCKLAND->value, TimezoneCode::PACIFIC_AUCKLAND->value],
            [TimezoneCode::PACIFIC_BOUGAINVILLE, TimezoneCode::PACIFIC_BOUGAINVILLE->value, TimezoneCode::PACIFIC_BOUGAINVILLE->value],
            [TimezoneCode::PACIFIC_CHATHAM, TimezoneCode::PACIFIC_CHATHAM->value, TimezoneCode::PACIFIC_CHATHAM->value],
            [TimezoneCode::PACIFIC_CHUUK, TimezoneCode::PACIFIC_CHUUK->value, TimezoneCode::PACIFIC_CHUUK->value],
            [TimezoneCode::PACIFIC_EASTER, TimezoneCode::PACIFIC_EASTER->value, TimezoneCode::PACIFIC_EASTER->value],
            [TimezoneCode::PACIFIC_EFATE, TimezoneCode::PACIFIC_EFATE->value, TimezoneCode::PACIFIC_EFATE->value],
            [TimezoneCode::PACIFIC_FAKAOFO, TimezoneCode::PACIFIC_FAKAOFO->value, TimezoneCode::PACIFIC_FAKAOFO->value],
            [TimezoneCode::PACIFIC_FIJI, TimezoneCode::PACIFIC_FIJI->value, TimezoneCode::PACIFIC_FIJI->value],
            [TimezoneCode::PACIFIC_FUNAFUTI, TimezoneCode::PACIFIC_FUNAFUTI->value, TimezoneCode::PACIFIC_FUNAFUTI->value],
            [TimezoneCode::PACIFIC_GALAPAGOS, TimezoneCode::PACIFIC_GALAPAGOS->value, TimezoneCode::PACIFIC_GALAPAGOS->value],
            [TimezoneCode::PACIFIC_GAMBIER, TimezoneCode::PACIFIC_GAMBIER->value, TimezoneCode::PACIFIC_GAMBIER->value],
            [TimezoneCode::PACIFIC_GUADALCANAL, TimezoneCode::PACIFIC_GUADALCANAL->value, TimezoneCode::PACIFIC_GUADALCANAL->value],
            [TimezoneCode::PACIFIC_GUAM, TimezoneCode::PACIFIC_GUAM->value, TimezoneCode::PACIFIC_GUAM->value],
            [TimezoneCode::PACIFIC_HONOLULU, TimezoneCode::PACIFIC_HONOLULU->value, TimezoneCode::PACIFIC_HONOLULU->value],
            [TimezoneCode::PACIFIC_KANTON, TimezoneCode::PACIFIC_KANTON->value, TimezoneCode::PACIFIC_KANTON->value],
            [TimezoneCode::PACIFIC_KIRITIMATI, TimezoneCode::PACIFIC_KIRITIMATI->value, TimezoneCode::PACIFIC_KIRITIMATI->value],
            [TimezoneCode::PACIFIC_KOSRAE, TimezoneCode::PACIFIC_KOSRAE->value, TimezoneCode::PACIFIC_KOSRAE->value],
            [TimezoneCode::PACIFIC_KWAJALEIN, TimezoneCode::PACIFIC_KWAJALEIN->value, TimezoneCode::PACIFIC_KWAJALEIN->value],
            [TimezoneCode::PACIFIC_MAJURO, TimezoneCode::PACIFIC_MAJURO->value, TimezoneCode::PACIFIC_MAJURO->value],
            [TimezoneCode::PACIFIC_MARQUESAS, TimezoneCode::PACIFIC_MARQUESAS->value, TimezoneCode::PACIFIC_MARQUESAS->value],
            [TimezoneCode::PACIFIC_MIDWAY, TimezoneCode::PACIFIC_MIDWAY->value, TimezoneCode::PACIFIC_MIDWAY->value],
            [TimezoneCode::PACIFIC_NAURU, TimezoneCode::PACIFIC_NAURU->value, TimezoneCode::PACIFIC_NAURU->value],
            [TimezoneCode::PACIFIC_NIUE, TimezoneCode::PACIFIC_NIUE->value, TimezoneCode::PACIFIC_NIUE->value],
            [TimezoneCode::PACIFIC_NORFOLK, TimezoneCode::PACIFIC_NORFOLK->value, TimezoneCode::PACIFIC_NORFOLK->value],
            [TimezoneCode::PACIFIC_NOUMEA, TimezoneCode::PACIFIC_NOUMEA->value, TimezoneCode::PACIFIC_NOUMEA->value],
            [TimezoneCode::PACIFIC_PAGO_PAGO, TimezoneCode::PACIFIC_PAGO_PAGO->value, TimezoneCode::PACIFIC_PAGO_PAGO->value],
            [TimezoneCode::PACIFIC_PALAU, TimezoneCode::PACIFIC_PALAU->value, TimezoneCode::PACIFIC_PALAU->value],
            [TimezoneCode::PACIFIC_PITCAIRN, TimezoneCode::PACIFIC_PITCAIRN->value, TimezoneCode::PACIFIC_PITCAIRN->value],
            [TimezoneCode::PACIFIC_POHNPEI, TimezoneCode::PACIFIC_POHNPEI->value, TimezoneCode::PACIFIC_POHNPEI->value],
            [TimezoneCode::PACIFIC_PORT_MORESBY, TimezoneCode::PACIFIC_PORT_MORESBY->value, TimezoneCode::PACIFIC_PORT_MORESBY->value],
            [TimezoneCode::PACIFIC_RAROTONGA, TimezoneCode::PACIFIC_RAROTONGA->value, TimezoneCode::PACIFIC_RAROTONGA->value],
            [TimezoneCode::PACIFIC_SAIPAN, TimezoneCode::PACIFIC_SAIPAN->value, TimezoneCode::PACIFIC_SAIPAN->value],
            [TimezoneCode::PACIFIC_TAHITI, TimezoneCode::PACIFIC_TAHITI->value, TimezoneCode::PACIFIC_TAHITI->value],
            [TimezoneCode::PACIFIC_TARAWA, TimezoneCode::PACIFIC_TARAWA->value, TimezoneCode::PACIFIC_TARAWA->value],
            [TimezoneCode::PACIFIC_TONGATAPU, TimezoneCode::PACIFIC_TONGATAPU->value, TimezoneCode::PACIFIC_TONGATAPU->value],
            [TimezoneCode::PACIFIC_WAKE, TimezoneCode::PACIFIC_WAKE->value, TimezoneCode::PACIFIC_WAKE->value],
            [TimezoneCode::PACIFIC_WALLIS, TimezoneCode::PACIFIC_WALLIS->value, TimezoneCode::PACIFIC_WALLIS->value],
            [TimezoneCode::UTC, TimezoneCode::UTC->value, TimezoneCode::UTC->value],
        ];
    }
}
